<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.acp.package
* generated at Fri, 30 Aug 2013 22:10:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.acp.package.cancel'] = 'Cancel package installation';
$this->items[$this->languageID]['wcf.acp.package.description'] = 'Description';
$this->items[$this->languageID]['wcf.acp.package.ftp'] = 'Enter the access details for FTP here.';
$this->items[$this->languageID]['wcf.acp.package.ftp.accessData'] = 'FTP access details';
$this->items[$this->languageID]['wcf.acp.package.ftp.description'] = 'With PHP Safe Mode being enabled on your server, the package needs to be installed with the help of FTP functions. Please enter the FTP user name and password for this server. The information you provide will not be recorded or forwarded to any other party and will solely be used for installation purposes. For this reason alone, it may be possible that the FTP details will be required to be entered again during the installation process.';
$this->items[$this->languageID]['wcf.acp.package.ftp.error'] = 'With the FTP details you have entered, no FTP connection could be made.';
$this->items[$this->languageID]['wcf.acp.package.ftp.error.cannotConnect'] = 'A connection to the specified FTP server could not be made.';
$this->items[$this->languageID]['wcf.acp.package.ftp.error.cannotLogin'] = 'A correct logon to the specified FTP server could not be made.';
$this->items[$this->languageID]['wcf.acp.package.ftp.host'] = 'Hostname';
$this->items[$this->languageID]['wcf.acp.package.ftp.password'] = 'Password';
$this->items[$this->languageID]['wcf.acp.package.ftp.user'] = 'Username';
$this->items[$this->languageID]['wcf.acp.package.install'] = 'Package Installation';
$this->items[$this->languageID]['wcf.acp.package.install.cancel'] = 'Cancel the installation';
$this->items[$this->languageID]['wcf.acp.package.install.cancel.sure'] = 'Are you sure you would like to cancel this installation?';
$this->items[$this->languageID]['wcf.acp.package.install.error'] = 'Package dependencies could not be satisfied for this Package.';
$this->items[$this->languageID]['wcf.acp.package.install.error.excludedPackages'] = 'The {if $action == \'install\'}package installation{else}package update{/if} of package &quot;{$packageName}&quot; in version {$packageVersion} cannot be executed due to incompatibilities with the following {if $excludedPackages|count == 1}package{else}packages{/if}:';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.error.excludedPackages'] = 'The <?php if ($this->v[\'action\'] == \'install\') { ?>package installation<?php } else { ?>package update<?php } ?> of package &quot;<?php echo StringUtil::encodeHTML($this->v[\'packageName\']); ?>&quot; in version <?php echo StringUtil::encodeHTML($this->v[\'packageVersion\']); ?> cannot be executed due to incompatibilities with the following <?php if (count($this->v[\'excludedPackages\']) == 1) { ?>package<?php } else { ?>packages<?php } ?>:';
$this->items[$this->languageID]['wcf.acp.package.install.error.excludedPackages.excludedPackage'] = '{$excludedPackage.packageName}{if $excludedPackage.instanceNo > 1} (#{@$excludedPackage.instanceNo}){/if} in version {$excludedPackage.packageVersion}';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.error.excludedPackages.excludedPackage'] = '<?php echo StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'packageName\']); ?><?php if ($this->v[\'excludedPackage\'][\'instanceNo\'] > 1) { ?> (#<?php echo $this->v[\'excludedPackage\'][\'instanceNo\']; ?>)<?php } ?> in version <?php echo StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'packageVersion\']); ?>';
$this->items[$this->languageID]['wcf.acp.package.install.error.excludingPackages'] = '{if $excludingPackages|count == 1}Following package doesn\'t{else}Following packages don\'t{/if} allow the {if $action == \'install\'}package installation{else}package update{/if} of package &quot;{$packageName}&quot; in version {$packageVersion} due to incompatibilities:';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.error.excludingPackages'] = '<?php if (count($this->v[\'excludingPackages\']) == 1) { ?>Following package doesn\'t<?php } else { ?>Following packages don\'t<?php } ?> allow the <?php if ($this->v[\'action\'] == \'install\') { ?>package installation<?php } else { ?>package update<?php } ?> of package &quot;<?php echo StringUtil::encodeHTML($this->v[\'packageName\']); ?>&quot; in version <?php echo StringUtil::encodeHTML($this->v[\'packageVersion\']); ?> due to incompatibilities:';
$this->items[$this->languageID]['wcf.acp.package.install.error.excludingPackages.excludingPackage'] = '{$excludingPackage.packageName}{if $excludingPackage.instanceNo > 1} (#{@$excludingPackage.instanceNo}){/if} in version {$excludingPackage.packageVersion}';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.error.excludingPackages.excludingPackage'] = '<?php echo StringUtil::encodeHTML($this->v[\'excludingPackage\'][\'packageName\']); ?><?php if ($this->v[\'excludingPackage\'][\'instanceNo\'] > 1) { ?> (#<?php echo $this->v[\'excludingPackage\'][\'instanceNo\']; ?>)<?php } ?> in version <?php echo StringUtil::encodeHTML($this->v[\'excludingPackage\'][\'packageVersion\']); ?>';
$this->items[$this->languageID]['wcf.acp.package.install.error.excludingPackages.warning'] = '{if $excludingPackages|count == 1}Following package is{else}Following packages are{/if} incompatible with package &quot;{$packageName}&quot; in version {$packageVersion}. If you proceed installation the {if $excludingPackages|count == 1}package{else}packages{/if} probably won\'t work anymore.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.error.excludingPackages.warning'] = '<?php if (count($this->v[\'excludingPackages\']) == 1) { ?>Following package is<?php } else { ?>Following packages are<?php } ?> incompatible with package &quot;<?php echo StringUtil::encodeHTML($this->v[\'packageName\']); ?>&quot; in version <?php echo StringUtil::encodeHTML($this->v[\'packageVersion\']); ?>. If you proceed installation the <?php if (count($this->v[\'excludingPackages\']) == 1) { ?>package<?php } else { ?>packages<?php } ?> probably won\'t work anymore.';
$this->items[$this->languageID]['wcf.acp.package.install.packageName'] = '<span{if $package.open == 0} style="color: green"{else}{if !$package.file|isset} style="color: red"{/if}{/if}>{$package.name} ({if $package.open == 0}Installed{else}{if $package.file|isset}is located within this Package{else}Not available{/if}{/if})</span>';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.packageName'] = '<span<?php if ($this->v[\'package\'][\'open\'] == 0) { ?> style="color: green"<?php } else { ?><?php if ( ! isset($this->v[\'package\'][\'file\'])) { ?> style="color: red"<?php } ?><?php } ?>><?php echo StringUtil::encodeHTML($this->v[\'package\'][\'name\']); ?> (<?php if ($this->v[\'package\'][\'open\'] == 0) { ?>Installed<?php } else { ?><?php if (isset($this->v[\'package\'][\'file\'])) { ?>is located within this Package<?php } else { ?>Not available<?php } ?><?php } ?>)</span>';
$this->items[$this->languageID]['wcf.acp.package.install.rollback.sure'] = 'Are you sure you would like to cancel the installation of this package?';
$this->items[$this->languageID]['wcf.acp.package.install.updatableInstances'] = 'The following packages can be updated with this package';
$this->items[$this->languageID]['wcf.acp.package.install.updatableInstances.description'] = 'Select one of the following packages, in order to update its version. If you would like to install the package again, please click on &quot;{lang}wcf.global.button.next{/lang}&quot;.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.install.updatableInstances.description'] = 'Select one of the following packages, in order to update its version. If you would like to install the package again, please click on &quot;Next &raquo;&quot;.';
$this->items[$this->languageID]['wcf.acp.package.install.updatableInstances.warning'] = 'A copy of this package is already installed. If you continue, a further copy of this package will be installed. If you would like to update an available copy of this package, please select the copy from the following list.';
$this->items[$this->languageID]['wcf.acp.package.install.version'] = 'Package Version:';
$this->items[$this->languageID]['wcf.acp.package.installDate'] = 'Installation date';
$this->items[$this->languageID]['wcf.acp.package.installation.file.error.unknown'] = 'While unpacking the files of this package the following error occured:';
$this->items[$this->languageID]['wcf.acp.package.installation.file.error.untarFailed'] = 'The following files could not be unpacked successfully. Please check if the destination folder is writable.';
$this->items[$this->languageID]['wcf.acp.package.installation.tables.conflict'] = 'Conflicting Tables';
$this->items[$this->languageID]['wcf.acp.package.installation.tables.dontAskAgainKeep'] = 'Do not overwrite these tables and do not ask me again for this installation.';
$this->items[$this->languageID]['wcf.acp.package.installation.tables.dontAskAgainOverride'] = 'Overwrite the existing tables and do not ask me again for this installation.';
$this->items[$this->languageID]['wcf.acp.package.installation.tables.solution'] = 'Required changes';
$this->items[$this->languageID]['wcf.acp.package.installation.tables.tableName'] = 'Tables affected';
$this->items[$this->languageID]['wcf.acp.package.installation.tables.warning'] = 'Existing database tables conflict with the tables required to be installed by this package. Please choose whether to overwrite these tables.';
$this->items[$this->languageID]['wcf.acp.package.list'] = 'Installed packages';
$this->items[$this->languageID]['wcf.acp.package.list.author'] = 'Author';
$this->items[$this->languageID]['wcf.acp.package.list.count'] = 'A total of {#$items} packages installed';
$this->dynamicItems[$this->languageID]['wcf.acp.package.list.count'] = 'A total of <?php echo StringUtil::formatNumeric($this->v[\'items\']); ?> packages installed';
$this->items[$this->languageID]['wcf.acp.package.list.date'] = 'Date';
$this->items[$this->languageID]['wcf.acp.package.list.id'] = 'ID';
$this->items[$this->languageID]['wcf.acp.package.list.name'] = 'Name';
$this->items[$this->languageID]['wcf.acp.package.list.other'] = 'Package';
$this->items[$this->languageID]['wcf.acp.package.list.plugin'] = 'Plugin';
$this->items[$this->languageID]['wcf.acp.package.list.standalone'] = 'Standalone application';
$this->items[$this->languageID]['wcf.acp.package.list.version'] = 'Version';
$this->items[$this->languageID]['wcf.acp.package.optionals'] = 'Install optional packages';
$this->items[$this->languageID]['wcf.acp.package.optionals.description'] = 'The selected package brings the following options. Please select those you would like to install.';
$this->items[$this->languageID]['wcf.acp.package.optionals.installed'] = ' (This Package is already installed.)';
$this->items[$this->languageID]['wcf.acp.package.optionals.openRequirements'] = ' (The requirements of this Package have not been fulfilled.)';
$this->items[$this->languageID]['wcf.acp.package.packageDir'] = 'Installation folder';
$this->items[$this->languageID]['wcf.acp.package.packageDir.description'] = '';
$this->items[$this->languageID]['wcf.acp.package.packageDir.error.alreadyInstalled'] = 'Another application is already installed in this folder.';
$this->items[$this->languageID]['wcf.acp.package.packageDir.error.invalid'] = 'This folder is not valid.';
$this->items[$this->languageID]['wcf.acp.package.packageDir.error.notWritable'] = 'This folder is not writable.';
$this->items[$this->languageID]['wcf.acp.package.packageDir.error.wcfDirLocked'] = 'This folder is already in use by the WoltLab Community Framework. Please choose a different location.';
$this->items[$this->languageID]['wcf.acp.package.packageDir.input'] = 'Please enter the installation folder name here.';
$this->items[$this->languageID]['wcf.acp.package.packageDir.url'] = 'This application is accessible through the following URL after installation in this folder:';
$this->items[$this->languageID]['wcf.acp.package.requirements'] = 'Select dependencies';
$this->items[$this->languageID]['wcf.acp.package.requirements.description'] = 'The current package requires another package that is already installed several times. Please choose the instance that is required.';
$this->items[$this->languageID]['wcf.acp.package.rollback'] = 'Rollback package installation';
$this->items[$this->languageID]['wcf.acp.package.shortPackageInfo'] = 'Version {$packageVersion} - {@$packageDate|date} - Copyright &copy; {$packageAuthor}';
$this->dynamicItems[$this->languageID]['wcf.acp.package.shortPackageInfo'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierDate\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierDate.class.php\');
$this->pluginObjects[\'TemplatePluginModifierDate\'] = new TemplatePluginModifierDate;
}
?>Version <?php echo StringUtil::encodeHTML($this->v[\'packageVersion\']); ?> - <?php echo $this->pluginObjects[\'TemplatePluginModifierDate\']->execute(array($this->v[\'packageDate\']), $this); ?> - Copyright &copy; <?php echo StringUtil::encodeHTML($this->v[\'packageAuthor\']); ?>';
$this->items[$this->languageID]['wcf.acp.package.startInstall'] = 'Install new package';
$this->items[$this->languageID]['wcf.acp.package.startInstall.error.noValidInstall'] = 'The chosen package has no valid installation routine.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.error.noValidPackage'] = 'The archive you have given is not a valid package.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.error.noValidUpdate'] = 'The package &quot;{$package->getName()}&quot; could not be updated with the supplied archive.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.startInstall.error.noValidUpdate'] = 'The package &quot;<?php echo StringUtil::encodeHTML($this->v[\'package\']->getName()); ?>&quot; could not be updated with the supplied archive.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.error.notFound'] = 'No files were found within the specified directory.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.error.uniqueAlreadyInstalled'] = 'The chosen package is already installed. Packages can not be installed more than one time.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.error.uploadFailed'] = 'The upload of the chosen archive has failed.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.source'] = 'Select package source';
$this->items[$this->languageID]['wcf.acp.package.startInstall.source.download'] = 'Enter the path of the package located on your server';
$this->items[$this->languageID]['wcf.acp.package.startInstall.source.download.description'] = 'Enter a direct path to the package-file here. An internet address can be used or alternatively the path to the package file using the server\'s file system.';
$this->items[$this->languageID]['wcf.acp.package.startInstall.source.upload'] = 'Upload package from your local computer';
$this->items[$this->languageID]['wcf.acp.package.startInstall.source.upload.description'] = 'Enter the package file to be uploaded from your computer here.';
$this->items[$this->languageID]['wcf.acp.package.startUpdate'] = 'Update Package &quot;{$package->getName()}&quot;';
$this->dynamicItems[$this->languageID]['wcf.acp.package.startUpdate'] = 'Update Package &quot;<?php echo StringUtil::encodeHTML($this->v[\'package\']->getName()); ?>&quot;';
$this->items[$this->languageID]['wcf.acp.package.step.install.ACPMenuPackageInstallationPlugin'] = 'Installing menu entries for the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.ACPTemplatePatchPackageInstallationPlugin'] = 'Installing template patches for the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.ACPTemplatesPackageInstallationPlugin'] = 'Installing templates for the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.EventListenerPackageInstallationPlugin'] = 'Installing event listener ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.FilesPackageInstallationPlugin'] = 'Unpacking package files ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.GroupOptionsPackageInstallationPlugin'] = 'Installing usergroup options ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.LanguagesPackageInstallationPlugin'] = 'Installing package languages ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.OptionsPackageInstallationPlugin'] = 'Installing package options ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.ScriptPackageInstallationPlugin'] = 'Executing special scripts ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.SqlPackageInstallationPlugin'] = 'Installing database entries...';
$this->items[$this->languageID]['wcf.acp.package.step.install.TemplatePatchPackageInstallationPlugin'] = 'Installing template patches ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.TemplatesPackageInstallationPlugin'] = 'Installing package templates ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.UserOptionsPackageInstallationPlugin'] = 'Installing user profile fields ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.exclusions'] = 'Checking for possible conflicts ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.execPackageInstallationPlugins'] = 'Executing package plugins ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.finish'] = 'Installation is complete';
$this->items[$this->languageID]['wcf.acp.package.step.install.optionals'] = 'Installing optional packages ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.package'] = 'Registering package ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.packageInstallationPlugins'] = 'Installing package plugins ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.parent'] = 'Parent package allocation is being done ...';
$this->items[$this->languageID]['wcf.acp.package.step.install.requirements'] = 'Checking dependencies ...';
$this->items[$this->languageID]['wcf.acp.package.step.title'] = 'Package <b>{$packageName|encodeJS}</b>: ';
$this->dynamicItems[$this->languageID]['wcf.acp.package.step.title'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierEncodejs\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php\');
$this->pluginObjects[\'TemplatePluginModifierEncodejs\'] = new TemplatePluginModifierEncodejs;
}
?>Package <b><?php echo StringUtil::encodeHTML($this->pluginObjects[\'TemplatePluginModifierEncodejs\']->execute(array($this->v[\'packageName\']), $this)); ?></b>:';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.ACPMenuPackageInstallationPlugin'] = 'Removing menu items from the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.ACPTemplatePatchPackageInstallationPlugin'] = 'Removing template patches of the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.ACPTemplatesPackageInstallationPlugin'] = 'Removing templates from the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.EventListenerPackageInstallationPlugin'] = 'Removing event listener ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.FilesPackageInstallationPlugin'] = 'Removing package files ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.GroupOptionsPackageInstallationPlugin'] = 'Removing usergroup options ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.LanguagesPackageInstallationPlugin'] = 'Removing package languages ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.OptionsPackageInstallationPlugin'] = 'Removing package options ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.SqlPackageInstallationPlugin'] = 'Removing database entries...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.TemplatePatchPackageInstallationPlugin'] = 'Removing template patches ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.TemplatesPackageInstallationPlugin'] = 'Removing package templates ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.UserOptionsPackageInstallationPlugin'] = 'Removing user profile fields ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.execPackageInstallationPlugins'] = 'Executing package plugins ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.finish'] = 'Package removal finished';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.optionals'] = 'Removing optional packages ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.packageInstallationPlugins'] = 'Removing package plugins ...';
$this->items[$this->languageID]['wcf.acp.package.step.uninstall.requirements'] = 'Removing package requirements ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.ACPMenuPackageInstallationPlugin'] = 'Updating menu items in the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.ACPTemplatePatchPackageInstallationPlugin'] = 'Updating template patches in the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.ACPTemplatesPackageInstallationPlugin'] = 'Updating templates in the Administration Control Panel ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.EventListenerPackageInstallationPlugin'] = 'Updating event listener ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.FilesPackageInstallationPlugin'] = 'Unpacking package files ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.GroupOptionsPackageInstallationPlugin'] = 'Updating usergroup options ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.LanguagesPackageInstallationPlugin'] = 'Updating package languages ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.OptionsPackageInstallationPlugin'] = 'Updating package options ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.ScriptPackageInstallationPlugin'] = 'Executing special scripts ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.SqlPackageInstallationPlugin'] = 'Updating database entries ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.TemplatePatchPackageInstallationPlugin'] = 'Updating template patches ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.TemplatesPackageInstallationPlugin'] = 'Updating package templates ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.UserOptionsPackageInstallationPlugin'] = 'Updating user profile fields ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.execPackageInstallationPlugins'] = 'Executing package plugins ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.exclusions'] = 'Checking for possible conflicts ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.finish'] = 'Package update finished';
$this->items[$this->languageID]['wcf.acp.package.step.update.optionals'] = 'Updating optional packages ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.package'] = 'Updating package ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.packageInstallationPlugins'] = 'Updating package plugins ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.parent'] = 'Parent package allocation is being done ...';
$this->items[$this->languageID]['wcf.acp.package.step.update.requirements'] = 'Checking dependencies ...';
$this->items[$this->languageID]['wcf.acp.package.templatePatch.install.failed'] = 'The patch that this package is trying to apply has failed because this patch is not compliant to its target file. Therefore this package cannot be installed. Please click the &quot;{lang}wcf.acp.package.install.cancel{/lang}&quot; button.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.templatePatch.install.failed'] = 'The patch that this package is trying to apply has failed because this patch is not compliant to its target file. Therefore this package cannot be installed. Please click the &quot;Cancel the installation&quot; button.';
$this->items[$this->languageID]['wcf.acp.package.templatePatch.repatch.failed'] = 'Re-patching of the following templates has failed:<br />{foreach from=$failures item=$failure}{$failure.templateName} (Originally patched by: {$failure.packageName})<br />{/foreach}The original patch package that was previously applied may no longer function. You should still continue with this update by clicking on the &quot;{lang}wcf.global.button.next{/lang}&quot; button.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.templatePatch.repatch.failed'] = 'Re-patching of the following templates has failed:<br /><?php
if (count($this->v[\'failures\']) > 0) {
foreach ($this->v[\'failures\'] as $this->v[\'failure\']) {
?><?php echo StringUtil::encodeHTML($this->v[\'failure\'][\'templateName\']); ?> (Originally patched by: <?php echo StringUtil::encodeHTML($this->v[\'failure\'][\'packageName\']); ?>)<br /><?php } } ?>The original patch package that was previously applied may no longer function. You should still continue with this update by clicking on the &quot;Next &raquo;&quot; button.';
$this->items[$this->languageID]['wcf.acp.package.templatePatch.uninstall.failed'] = 'The patch that this package is trying to remove has failed because its target file has been externally amended. Therefore this package cannot be removed. Please click the &quot;{lang}wcf.acp.package.uninstall.cancel{/lang}&quot; button.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.templatePatch.uninstall.failed'] = 'The patch that this package is trying to remove has failed because its target file has been externally amended. Therefore this package cannot be removed. Please click the &quot;wcf.acp.package.uninstall.cancel&quot; button.';
$this->items[$this->languageID]['wcf.acp.package.uninstall'] = 'Package removal';
$this->items[$this->languageID]['wcf.acp.package.uninstall.cancel'] = 'Cancel package-removal';
$this->items[$this->languageID]['wcf.acp.package.uninstall.dependentPackages.error'] = 'It is not possible to uninstall these packages, because there is at least one dependent package, that cannot be uninstalled.';
$this->items[$this->languageID]['wcf.acp.package.uninstall.dependentPackages.warning'] = 'Upon final confirmation {if $dependentPackages|count == 1}this package{else}these packages{/if} will be removed without any further promting.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.uninstall.dependentPackages.warning'] = 'Upon final confirmation <?php if (count($this->v[\'dependentPackages\']) == 1) { ?>this package<?php } else { ?>these packages<?php } ?> will be removed without any further promting.';
$this->items[$this->languageID]['wcf.acp.package.update'] = 'Package update';
$this->items[$this->languageID]['wcf.acp.package.updateDate'] = 'Date of update';
$this->items[$this->languageID]['wcf.acp.package.view.author'] = 'Author:';
$this->items[$this->languageID]['wcf.acp.package.view.button.makeActive'] = 'Go to the Administration Control Panel';
$this->items[$this->languageID]['wcf.acp.package.view.button.uninstall'] = 'Remove package';
$this->items[$this->languageID]['wcf.acp.package.view.button.uninstall.all'] = 'Remove all packages';
$this->items[$this->languageID]['wcf.acp.package.view.button.uninstall.sure'] = 'Are you sure that you would like to remove this package?';
$this->items[$this->languageID]['wcf.acp.package.view.button.update'] = 'Update package';
$this->items[$this->languageID]['wcf.acp.package.view.date'] = 'Date:';
$this->items[$this->languageID]['wcf.acp.package.view.dependentPackages'] = 'Dependent packages';
$this->items[$this->languageID]['wcf.acp.package.view.dependentPackages.description'] = 'This package has a requirement from {if $dependentPackages|count == 1}one other package.{else}{#$dependentPackages|count} other packages.{/if}';
$this->dynamicItems[$this->languageID]['wcf.acp.package.view.dependentPackages.description'] = 'This package has a requirement from <?php if (count($this->v[\'dependentPackages\']) == 1) { ?>one other package.<?php } else { ?><?php echo StringUtil::formatNumeric(count($this->v[\'dependentPackages\'])); ?> other packages.<?php } ?>';
$this->items[$this->languageID]['wcf.acp.package.view.dependentPackages.uninstall.description'] = '{if $dependentPackages|count == 1}This package is required by one other Package{else}{#$dependentPackages|count} Packages are directly or indirectly dependent upon this package{/if}.';
$this->dynamicItems[$this->languageID]['wcf.acp.package.view.dependentPackages.uninstall.description'] = '<?php if (count($this->v[\'dependentPackages\']) == 1) { ?>This package is required by one other Package<?php } else { ?><?php echo StringUtil::formatNumeric(count($this->v[\'dependentPackages\'])); ?> Packages are directly or indirectly dependent upon this package<?php } ?>.';
$this->items[$this->languageID]['wcf.acp.package.view.dir'] = 'Installation folder:';
$this->items[$this->languageID]['wcf.acp.package.view.identifier'] = 'Identifier:';
$this->items[$this->languageID]['wcf.acp.package.view.instanceNo'] = 'Installed instance:';
$this->items[$this->languageID]['wcf.acp.package.view.parent'] = 'Parent package:';
$this->items[$this->languageID]['wcf.acp.package.view.properties'] = 'Properties';
$this->items[$this->languageID]['wcf.acp.package.view.requiredPackages'] = 'Required packages';
$this->items[$this->languageID]['wcf.acp.package.view.requiredPackages.description'] = 'This package has a requirement of {if $requiredPackages|count == 1}one other package.{else}{#$requiredPackages|count} other packages.{/if}';
$this->dynamicItems[$this->languageID]['wcf.acp.package.view.requiredPackages.description'] = 'This package has a requirement of <?php if (count($this->v[\'requiredPackages\']) == 1) { ?>one other package.<?php } else { ?><?php echo StringUtil::formatNumeric(count($this->v[\'requiredPackages\'])); ?> other packages.<?php } ?>';
$this->items[$this->languageID]['wcf.acp.package.view.url'] = 'Homepage:';
$this->items[$this->languageID]['wcf.acp.package.view.version'] = 'Installed version:';
?>