<?php
/**
* WoltLab Community Framework
* Template: accountManagement
* Compiled at: Sat, 31 Aug 2013 15:28:45 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'accountManagement';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierDate'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierDate.class.php');
$this->pluginObjects['TemplatePluginModifierDate'] = new TemplatePluginModifierDate;
}
?><?php
$outerTemplateNameed1398df52972d03343749918bbfca537035957e = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameed1398df52972d03343749918bbfca537035957e;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>User account - Edit profile - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang98998f84353905a8fbb1a80fe7753bd5b0f7e073 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang98998f84353905a8fbb1a80fe7753bd5b0f7e073, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName7f0ceab8e470c29eb8cda537872c605be38babe3 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7f0ceab8e470c29eb8cda537872c605be38babe3;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName658ec0bd2efd17fa21af1aa47e0f0ba1f35387d2 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName658ec0bd2efd17fa21af1aa47e0f0ba1f35387d2;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php ob_start(); ?>
		<?php if ($this->v['errorField']) { ?>
			<p class="error">The data you have entered are invalid. Please check the information you have given in the marked fields.</p>
		<?php } ?>
		
		<?php if (isset($this->v['success']) && count($this->v['success']) > 0) { ?>
			<div class="success">
				<?php
if (count($this->v['success']) > 0) {
foreach ($this->v['success'] as $this->v['successMessage']) {
?>
					<p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['successMessage']; ?><?php $_langf47a6531ecbb2468427498dcc3e27b799efce8d5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langf47a6531ecbb2468427498dcc3e27b799efce8d5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
				<?php } } ?>
			</div>
		<?php } ?>
	<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->append('userMessages', $this->v['tpl']['capture']['default']);
?>
	
	<?php
$outerTemplateName7779b28e68e4411ae6c063281f6b67a6e802d314 = $this->v['tpl']['template'];
$this->includeTemplate("userCPHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7779b28e68e4411ae6c063281f6b67a6e802d314;
$this->v['tpl']['includedTemplates']["userCPHeader"] = 1;
?>
	
	<form method="post" action="index.php?form=AccountManagement">
		<div class="border tabMenuContent">
			<div class="container-1">
				<h3 class="subHeadline">User account</h3>
				
				<p class="warning">You are editing your own user account. Unthought changes might lock you out of your account. Please be careful!</p>
				
				<div class="formElement<?php if ($this->v['errorField'] == 'password') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="password">Password</label>
					</div>
					<div class="formField">
						<input type="password" class="inputText" name="password" value="<?php echo StringUtil::encodeHTML($this->v['password']); ?>" id="password" />
						<?php if ($this->v['errorField'] == 'password') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
								<?php if ($this->v['errorType'] == 'false') { ?>The password you entered is invalid. If you have lost your password you can use the <a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">&quot;Lost Password&quot; function</a>.<?php } ?>
							</p>
						<?php } ?>
					</div>
					<div class="formFieldDesc">
						<p>Please enter your password for confirmation!</p>
					</div>
				</div>
				
				<?php if ($this->v['canChangeUsername']) { ?>
					<fieldset>
						<legend><label for="username">Change username</label></legend>
						
						<div class="formElement<?php if ($this->v['errorField'] == 'username') { ?> formError<?php } ?>">
							<div class="formFieldLabel">
								<label for="username">Username</label>
							</div>
							
							<div class="formField">
								<input type="text" class="inputText" name="username" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" id="username" />
								
								<?php if ($this->v['errorField'] == 'username') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
										<?php if ($this->v['errorType'] == 'notValid') { ?>The username you have entered is not valid.<?php } ?>
										<?php if ($this->v['errorType'] == 'notUnique') { ?>The user name you have entered is already in use.<?php } ?>
										<?php if ($this->v['errorType'] == 'notChanged') { ?>The new username is identical with the old one.<?php } ?>
									</p>
								<?php } ?>
							</div>
							<?php if ($this->v['renamePeriod'] > 0) { ?>
								<div class="formFieldDesc">
									<p>You can change your username only once in <?php echo StringUtil::encodeHTML($this->v['renamePeriod']); ?> days. Changes from uppercase to lowercase are possible without a limit.</p>
								</div>
							<?php } ?>
						</div>
					</fieldset>
				<?php } ?>
				
				<fieldset>
					<legend><label for="newPassword">Change password</label></legend>
					
					<div class="formElement<?php if ($this->v['errorField'] == 'newPassword') { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="newPassword">New password</label>
						</div>
						<div class="formField">
							<input type="password" class="inputText" name="newPassword" value="<?php echo StringUtil::encodeHTML($this->v['newPassword']); ?>" id="newPassword" />
							
							<?php if ($this->v['errorField'] == 'newPassword') { ?>
								<p class="innerError">
									<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
									<?php if ($this->v['errorType'] == 'notSecure') { ?>For security reasons the password should contain at least <?php echo StringUtil::encodeHTML(REGISTER_PASSWORD_MIN_LENGTH); ?> characters<?php if (REGISTER_PASSWORD_MUST_CONTAIN_LOWER_CASE || REGISTER_PASSWORD_MUST_CONTAIN_UPPER_CASE || REGISTER_PASSWORD_MUST_CONTAIN_DIGIT || REGISTER_PASSWORD_MUST_CONTAIN_SPECIAL_CHAR) { ?>
		and
		<?php if (REGISTER_PASSWORD_MUST_CONTAIN_LOWER_CASE) { ?>small letters<?php } ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_UPPER_CASE) { ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_LOWER_CASE) { ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_DIGIT || REGISTER_PASSWORD_MUST_CONTAIN_SPECIAL_CHAR) { ?>,<?php } else { ?> and<?php } ?> <?php } ?>capital letters<?php } ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_DIGIT) { ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_LOWER_CASE || REGISTER_PASSWORD_MUST_CONTAIN_UPPER_CASE) { ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_SPECIAL_CHAR) { ?>,<?php } else { ?> and<?php } ?> <?php } ?>digits<?php } ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_SPECIAL_CHAR) { ?><?php if (REGISTER_PASSWORD_MUST_CONTAIN_LOWER_CASE || REGISTER_PASSWORD_MUST_CONTAIN_UPPER_CASE || REGISTER_PASSWORD_MUST_CONTAIN_DIGIT) { ?> and <?php } ?>special characters<?php } ?>
		<?php } ?>.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
					
					<div class="formElement<?php if ($this->v['errorField'] == 'confirmNewPassword') { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="confirmNewPassword">Repeat new password</label>
						</div>
						<div class="formField">
							<input type="password" class="inputText" name="confirmNewPassword" value="<?php echo StringUtil::encodeHTML($this->v['confirmNewPassword']); ?>" id="confirmNewPassword" />
							
							<?php if ($this->v['errorField'] == 'confirmNewPassword') { ?>
								<p class="innerError">
									<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
									<?php if ($this->v['errorType'] == 'notEqual') { ?>The given password and confirmation password are not identical.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
				</fieldset>
				
				<?php if ($this->v['this']->user->getPermission('user.profile.canChangeEmail')) { ?>
					<fieldset>
						<legend><label for="email">Change e-mail address</label></legend>
						
						<div class="formElement<?php if ($this->v['errorField'] == 'email') { ?> formError<?php } ?>">
							<div class="formFieldLabel">
								<label for="email">E-mail Address</label>
							</div>
							<div class="formField">
								<input type="text" class="inputText" name="email" value="<?php echo StringUtil::encodeHTML($this->v['email']); ?>" id="email" />
								
								<?php if ($this->v['errorField'] == 'email') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
										<?php if ($this->v['errorType'] == 'notValid') { ?>The e-mail address you have entered is not valid.<?php } ?>
										<?php if ($this->v['errorType'] == 'notUnique') { ?>The e-mail address you have entered has already been used by another user.<?php } ?>
										<?php if ($this->v['errorType'] == 'notChanged') { ?>wcf.user.emailChange.error.email.notChanged<?php } ?>
									</p>
								<?php } ?>
							</div>
						</div>
						
						<div class="formElement<?php if ($this->v['errorField'] == 'confirmEmail') { ?> formError<?php } ?>">
							<div class="formFieldLabel">
								<label for="confirmEmail">Confirm E-mail Address</label>
							</div>
							<div class="formField">
								<input type="text" class="inputText" name="confirmEmail" value="<?php echo StringUtil::encodeHTML($this->v['confirmEmail']); ?>" id="confirmEmail" />
								
								<?php if ($this->v['errorField'] == 'confirmEmail') { ?>
									<p class="innerError">
										<?php if ($this->v['errorType'] == 'notEqual') { ?>The given e-mail address and confirmation e-mail address are not identical.<?php } ?>
									</p>
								<?php } ?>
							</div>
						</div>
						
						<?php if (REGISTER_ACTIVATION_METHOD == 1 && $this->v['this']->user->reactivationCode != 0) { ?>
							<div class="formElement">
								<div class="formField">
									<ul class="formOptionsLong">
										<li><img src="<?php ob_start(); ?>emailS.png<?php $_icon42c862ad9fdcf065e7be75159631a45cdabe5767 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon42c862ad9fdcf065e7be75159631a45cdabe5767); ?>" alt="" /> <a href="index.php?page=Register&amp;action=reenable<?php echo SID_ARG_2ND; ?>">Enable new e-mail address</a></li>
									</ul>
								</div>
							</div>
						<?php } ?>
					</fieldset>
				<?php } ?>
				
				<?php if ($this->v['this']->user->getPermission('user.profile.canQuit')) { ?>
					<fieldset>
						<legend>Quit user account</legend>
					
						<?php if ($this->v['quitStarted']) { ?>
							<div class="formElement">
								<div class="formField">
									<label><input type="checkbox" name="cancelQuit" value="1" <?php if ($this->v['cancelQuit'] == 1) { ?>checked="checked" <?php } ?>/> Your user account will be deleted at <?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierDate']->execute(array($this->v['quitStarted']+7*86400,null), $this)); ?>. Please enable this option if you do not want to cancel the deletion.</label>
								</div>
							</div>
						<?php } else { ?>
							<div class="formElement">
								<div class="formField">
									<label><input type="checkbox" name="quit" value="1" <?php if ($this->v['quit'] == 1) { ?>checked="checked" <?php } ?>/> Do you really want to permanently delete your user account and your personal data?</label>
								</div>
								<div class="formFieldDesc">
									<p>Note: This action does not delete posts, attachments and other user generated content.</p>
								</div>
							</div>
						<?php } ?>
					</fieldset>
				<?php } ?>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
			</div>
		</div>
		
		<div class="formSubmit">
			<?php echo SID_INPUT_TAG; ?>
			<?php echo SECURITY_TOKEN_INPUT_TAG; ?>
			<input type="submit" accesskey="s" value="Submit" />
			<input type="reset" accesskey="r" value="Reset" />
		</div>
	</form>
	
</div>

<?php
$outerTemplateName97a4b10fc8ac7395ef5ed82e7f406c17dc5ff42b = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName97a4b10fc8ac7395ef5ed82e7f406c17dc5ff42b;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>