<?php
/**
* WoltLab Community Framework
* Template: userProfile
* Compiled at: Sat, 31 Aug 2013 10:57:22 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userProfile';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginModifierTime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierTime.class.php');
$this->pluginObjects['TemplatePluginModifierTime'] = new TemplatePluginModifierTime;
}
?><?php
$outerTemplateName2dcad034374827ca8f174c09a33ebf7c0a90739a = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2dcad034374827ca8f174c09a33ebf7c0a90739a;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Profile of &quot;<?php echo StringUtil::encodeHTML($this->v['user']->username); ?>&quot; - Members - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang4fdab1195998ef52906d9cf8cc867ecc1e151464 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang4fdab1195998ef52906d9cf8cc867ecc1e151464, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName0375e98751dfa90e81831e277296d52012a5dd78 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName0375e98751dfa90e81831e277296d52012a5dd78;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<script type="text/javascript">
		//<![CDATA[
		var INLINE_IMAGE_MAX_WIDTH = <?php echo INLINE_IMAGE_MAX_WIDTH; ?>; 
		//]]>
	</script>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/ImageResizer.class.js"></script>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>

<?php $this->assign('searchFieldTitle', 'Search user posts'); ?>
<?php ob_start(); ?>
	<input type="hidden" name="userID" value="<?php echo $this->v['user']->userID; ?>" />
<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->assign('searchHiddenFields', $this->v['tpl']['capture']['default']);
?>

<?php
$outerTemplateName914e26fc3ad511e64c4e0676db797bc9a1f64962 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName914e26fc3ad511e64c4e0676db797bc9a1f64962;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	<?php
$outerTemplateNamec1291c94e036f9bfe3a6273b000f067dac26a4bd = $this->v['tpl']['template'];
$this->includeTemplate("userProfileHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamec1291c94e036f9bfe3a6273b000f067dac26a4bd;
$this->v['tpl']['includedTemplates']["userProfileHeader"] = 1;
?>
	
	<div class="border">
		<div class="layout-2">
			<div class="columnContainer">	
				<div class="container-1 column first">
					<div class="columnInner">
						
						<?php if (isset($this->v['additionalContent1'])) { ?><?php echo $this->v['additionalContent1']; ?><?php } ?>
					
						<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2', 'print' => false, 'advance' => false), $this); ?>

						<?php
if (count($this->v['categories']) > 0) {
foreach ($this->v['categories'] as $this->v['category']) {
?>
							<div class="contentBox">
								<h3 class="subHeadline"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo StringUtil::encodeHTML($this->v['category']['categoryName']); ?><?php $_lang374d559309f30cda4345e94a39c315670f248f47 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang374d559309f30cda4345e94a39c315670f248f47, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h3>
								
								<ul class="dataList">
									<?php
if (count($this->v['category']['options']) > 0) {
foreach ($this->v['category']['options'] as $this->v['option']) {
?>
										<?php if ($this->v['option']['optionName'] == 'aboutMe') { ?>
											<li class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> messageBody">
												<?php echo $this->v['option']['optionValue']; ?>
											</li>
										<?php } else { ?>
											<li class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> formElement">
												<p class="formFieldLabel"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.<?php echo StringUtil::encodeHTML($this->v['option']['optionName']); ?><?php $_lang4efd3cdd90ae88734e0d26072d477c5a97112bb1 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang4efd3cdd90ae88734e0d26072d477c5a97112bb1, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
												<p class="formField"><?php echo $this->v['option']['optionValue']; ?></p>
											</li>
										<?php } ?>
									<?php } } ?>
								</ul>
								
								<?php if ($this->v['category']['categoryName'] == 'profile.aboutMe') { ?>
									<?php if (isset($this->v['additionalAboutMeContent'])) { ?><?php echo $this->v['additionalAboutMeContent']; ?><?php } ?>
								<?php } ?>
								
								<div class="buttonBar">
									<div class="smallButtons">
										<ul><li class="extraButton"><a href="#top" title="Go to the top of the page"><img src="<?php ob_start(); ?>upS.png<?php $_icon5199d5bf01f24a3e71cded50b0838588cbc3d9eb = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon5199d5bf01f24a3e71cded50b0838588cbc3d9eb); ?>" alt="Go to the top of the page" /> <span class="hidden">Go to the top of the page</span></a></li></ul>
									</div>
								</div>
							</div>
						<?php } } else { { ?>
							<div class="contentBox">
								<h3 class="subHeadline">About me</h3>
								
								<div class="messageBody">This user has not entered any personal information yet.</div>
								
								<?php if (isset($this->v['additionalAboutMeContent'])) { ?><?php echo $this->v['additionalAboutMeContent']; ?><?php } ?>
								
								<div class="buttonBar">
									<div class="smallButtons">
										<ul><li class="extraButton"><a href="#top" title="Go to the top of the page"><img src="<?php ob_start(); ?>upS.png<?php $_icon08ba5bf422b98dae93d31075d7ace251f6ea66e6 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon08ba5bf422b98dae93d31075d7ace251f6ea66e6); ?>" alt="Go to the top of the page" /> <span class="hidden">Go to the top of the page</span></a></li></ul>
									</div>
								</div>						
							</div>	
						<?php } } ?>
						
						<?php if (isset($this->v['additionalContent2'])) { ?><?php echo $this->v['additionalContent2']; ?><?php } ?>
						
						<?php if (count($this->v['friends']) > 0) { ?>
							<div class="contentBox">
								<h3 class="subHeadline"><a href="index.php?page=UserFriendList&amp;userID=<?php echo $this->v['userID']; ?><?php echo SID_ARG_2ND; ?>">Friends</a> <span>(<?php echo StringUtil::formatNumeric($this->v['user']->friends); ?>)</span></h3>
								
								<ul class="dataList thumbnailView floatContainer container-1">
									<?php
$this->v['tpl']['foreach']['friends']['total'] = count($this->v['friends']);
$this->v['tpl']['foreach']['friends']['show'] = ($this->v['tpl']['foreach']['friends']['total'] > 0 ? true : false);
$this->v['tpl']['foreach']['friends']['iteration'] = 0;
if (count($this->v['friends']) > 0) {
foreach ($this->v['friends'] as $this->v['friend']) {
$this->v['tpl']['foreach']['friends']['first'] = ($this->v['tpl']['foreach']['friends']['iteration'] == 0 ? true : false);
$this->v['tpl']['foreach']['friends']['last'] = (($this->v['tpl']['foreach']['friends']['iteration'] == $this->v['tpl']['foreach']['friends']['total'] - 1) ? true : false);
$this->v['tpl']['foreach']['friends']['iteration']++;
?>
										<li class="floatedElement smallFont<?php if ($this->v['tpl']['foreach']['friends']['iteration'] == 5) { ?> last<?php } ?>">
											<a href="index.php?page=User&amp;userID=<?php echo $this->v['friend']->userID; ?><?php echo SID_ARG_2ND; ?>" title="<?php $this->tagStack[] = array('lang', array('username' => StringUtil::encodeHTML($this->v['friend']->username))); ob_start(); ?>wcf.user.viewProfile<?php $_lang92cac2b44777c3ff1b58edd30d4095b9562d2ac5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang92cac2b44777c3ff1b58edd30d4095b9562d2ac5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>">
												<?php if ($this->v['friend']->getAvatar()) { ?>
													<?php $this->assign('x', $this->v['friend']->getAvatar()->setMaxSize(48,48)); ?>
													<span class="thumbnail" style="width: <?php echo $this->v['friend']->getAvatar()->getWidth(); ?>px;"><?php echo $this->v['friend']->getAvatar(); ?></span>
												<?php } else { ?>
													<span class="thumbnail" style="width: 48px;"><img src="<?php echo RELATIVE_WCF_DIR; ?>images/avatars/avatar-default.png" alt="" style="width: 48px; height: 48px" /></span>
												<?php } ?>
												<span class="avatarCaption"><?php echo StringUtil::encodeHTML($this->v['friend']->username); ?></span>
											</a>
										</li>
									<?php } } ?>
								</ul>
								<div class="buttonBar">
									<div class="smallButtons">
										<ul>
											<li class="extraButton"><a href="#top" title="Go to the top of the page"><img src="<?php ob_start(); ?>upS.png<?php $_iconfa879a2b89176823821703d75b111c64e9489ccb = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconfa879a2b89176823821703d75b111c64e9489ccb); ?>" alt="Go to the top of the page" /> <span class="hidden">Go to the top of the page</span></a></li>
											<li><a href="index.php?page=UserFriendList&amp;userID=<?php echo $this->v['userID']; ?><?php echo SID_ARG_2ND; ?>" title="Show all friends"><img src="<?php ob_start(); ?>friendsS.png<?php $_icon97efb69c592b91516dfea1198677f42262741f03 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon97efb69c592b91516dfea1198677f42262741f03); ?>" alt="" /> <span>Show all friends</span></a></li>
										</ul>
									</div>
								</div>
							</div>
						<?php } ?>
						
						<?php if (isset($this->v['additionalContent3'])) { ?><?php echo $this->v['additionalContent3']; ?><?php } ?>
					</div>
				</div>
					
				<div class="container-3 column second sidebar profileSidebar">
					<div class="columnInner">
					
						<?php if (isset($this->v['additionalBoxes1'])) { ?><?php echo $this->v['additionalBoxes1']; ?><?php } ?>
					
						<?php if (count($this->v['contactInformation']) > 0) { ?>
							<div class="contentBox">
								<div class="border"> 
									<div class="containerHead"> 
										<h3>Contact</h3> 
									</div> 
									<div class="pageMenu"> 
										<ul class="twoRows">
											<?php
if (count($this->v['contactInformation']) > 0) {
foreach ($this->v['contactInformation'] as $this->v['contact']) {
?>
												<li class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2'), $this); ?>">
													<a<?php if ($this->v['contact']['url']) { ?> href="<?php echo $this->v['contact']['url']; ?>"<?php } ?>><?php if ($this->v['contact']['icon']) { ?><img src="<?php echo $this->v['contact']['icon']; ?>" alt="" /> <?php } ?><label class="smallFont"><?php echo $this->v['contact']['title']; ?></label> <span><?php echo $this->v['contact']['value']; ?></span></a>
												</li>
											<?php } } ?>
										</ul>
									</div> 
								</div>
							</div>
						<?php } ?>
						
						<?php if (count($this->v['generalInformation']) > 0) { ?>
							<div class="contentBox">
								<div class="border">
									<div class="containerHead">
										<h3>General information</h3>
									</div>
									
									<ul class="dataList">
										<?php
if (count($this->v['generalInformation']) > 0) {
foreach ($this->v['generalInformation'] as $this->v['general']) {
?>
											<li class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2'), $this); ?>">
												<div class="containerIcon">
													<?php if ( ! empty($this->v['general']['icon'])) { ?><img src="<?php echo $this->v['general']['icon']; ?>" alt="" title="<?php echo $this->v['general']['title']; ?>" /><?php } ?>
												</div>
												<div class="containerContent">
													<h4 class="smallFont"><?php echo $this->v['general']['title']; ?></h4>
													<p><?php echo $this->v['general']['value']; ?></p>
												</div>
											</li>
										<?php } } ?>
									</ul>
								</div>
							</div>
						<?php } ?>
						
						<?php if (isset($this->v['additionalBoxes2'])) { ?><?php echo $this->v['additionalBoxes2']; ?><?php } ?>
					
						<?php if (count($this->v['profileVisitors']) > 0) { ?>
							<div class="contentBox">
								<div class="border">
									<div class="containerHead">
										<h3>Visitors</h3>
									</div>
									
									<ul class="dataList">
										<?php
if (count($this->v['profileVisitors']) > 0) {
foreach ($this->v['profileVisitors'] as $this->v['profileVisitor']) {
?>
											<li class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2'), $this); ?>">
												<div class="containerIcon">
													<a href="index.php?page=User&amp;userID=<?php echo $this->v['profileVisitor']->userID; ?><?php echo SID_ARG_2ND; ?>" title="<?php $this->tagStack[] = array('lang', array('username' => StringUtil::encodeHTML($this->v['profileVisitor']->username))); ob_start(); ?>wcf.user.viewProfile<?php $_lang6748923701591d29c152ce6166f46f7b54c6bff2 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6748923701591d29c152ce6166f46f7b54c6bff2, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>">
														<?php if ($this->v['profileVisitor']->getAvatar()) { ?>
															<?php $this->assign('x', $this->v['profileVisitor']->getAvatar()->setMaxSize(24,24)); ?>
															<?php echo $this->v['profileVisitor']->getAvatar(); ?>
														<?php } else { ?>
															<img src="<?php echo RELATIVE_WCF_DIR; ?>images/avatars/avatar-default.png" alt="" style="width: 24px; height: 24px" />
														<?php } ?>
													</a>
												</div>
												<div class="containerContent">
													<h4><a href="index.php?page=User&amp;userID=<?php echo $this->v['profileVisitor']->userID; ?><?php echo SID_ARG_2ND; ?>" title="<?php $this->tagStack[] = array('lang', array('username' => StringUtil::encodeHTML($this->v['profileVisitor']->username))); ob_start(); ?>wcf.user.viewProfile<?php $_lang4312c7e1b7b8d1e369dd58e3afbb0d61143e64ec = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang4312c7e1b7b8d1e369dd58e3afbb0d61143e64ec, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>"><?php echo StringUtil::encodeHTML($this->v['profileVisitor']->username); ?></a></h4>
													<p class="light smallFont"><?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['profileVisitor']->time), $this); ?></p>
												</div>
											</li>
										<?php } } ?>
									</ul>
								</div>
							</div>
						<?php } ?>
						
						<?php if (isset($this->v['additionalBoxes3'])) { ?><?php echo $this->v['additionalBoxes3']; ?><?php } ?>
		
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php
$outerTemplateName29993c60655f72694d7e5db53abb3999a2140229 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName29993c60655f72694d7e5db53abb3999a2140229;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>