<?php
/**
* WoltLab Community Framework
* Template: search
* Compiled at: Sat, 31 Aug 2013 10:10:17 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'search';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><?php
$outerTemplateName8a857386acb4bc98ffa37db10ad27d97328fcb9c = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName8a857386acb4bc98ffa37db10ad27d97328fcb9c;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Search - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang78bc719ed839f66b421e13da31f8863c5aa77f16 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang78bc719ed839f66b421e13da31f8863c5aa77f16, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName6999bd7b8de3ceae3c408c2be88a85e73244913d = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName6999bd7b8de3ceae3c408c2be88a85e73244913d;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>

	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/Suggestion.class.js"></script>
	<script src="<?php echo RELATIVE_WCF_DIR; ?>js/Calendar.class.js" type="text/javascript"></script>
	<script type="text/javascript">
		//<![CDATA[
		function showSearchForm(formID, show) {
			if (show) {
				document.getElementById(formID).style.display = 'block';
			}
			else {
				document.getElementById(formID).style.display = 'none';
			}
		}
		
		var calendar = new Calendar('<?php echo StringUtil::encodeHTML($this->v['monthList']); ?>', '<?php echo StringUtil::encodeHTML($this->v['weekdayList']); ?>', <?php echo $this->v['startOfWeek']; ?>);
		//]]>
	</script>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php $this->assign('searchShowExtendedLink', false); ?>
<?php
$outerTemplateName7a13d8da759d0dd7efbbf4a07e629dce19472afe = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7a13d8da759d0dd7efbbf4a07e629dce19472afe;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php ob_start(); ?>indexS.png<?php $_icon269f73c959f364f734a262b956444259dd65e4d8 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon269f73c959f364f734a262b956444259dd65e4d8); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langae63b7dae18df0365ead171348236b3d7b890df9 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langae63b7dae18df0365ead171348236b3d7b890df9, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>
	
	<div class="mainHeadline">
		<img src="<?php ob_start(); ?>searchL.png<?php $_icon698f27186d5ecb8816a6835e78451f8d2770bd1d = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon698f27186d5ecb8816a6835e78451f8d2770bd1d); ?>" alt="" />
		<div class="headlineContainer">
			<h2>Search</h2>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if ($this->v['errorField']) { ?>
		<p class="error">The data you have entered are invalid. Please check the information you have given in the marked fields.</p>
	<?php } ?>
	
	<?php if (isset($this->v['errorMessage'])) { ?>
		<p class="error"><?php echo $this->v['errorMessage']; ?></p>
	<?php } ?>
	
	<form method="post" action="index.php?form=Search">
		<div class="border content">
			<div class="container-1">
			
				<?php if (isset($this->v['additionalBoxes1'])) { ?><?php echo $this->v['additionalBoxes1']; ?><?php } ?>
				
				<fieldset>
					<legend>General search terms</legend>
					<div class="formElement<?php if ($this->v['errorField'] == 'q') { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="searchTerm">Search by key words</label>
						</div>
						<div class="formField">
							<input type="text" class="inputText" id="searchTerm" name="q" value="<?php if ($this->v['query']) { ?><?php echo StringUtil::encodeHTML($this->v['query']); ?><?php } else { ?><?php echo StringUtil::encodeHTML($this->v['defaultQuery']); ?><?php } ?>" maxlength="255" />
							
							<?php if (isset($this->v['additionalQueryOptions'])) { ?><?php echo $this->v['additionalQueryOptions']; ?><?php } ?>
						</div>
						<div class="formFieldDesc">
							<p>Enter one or more terms. One term has to contain at least four characters.<?php if (MODULE_HELP) { ?> All search possibilities you can find within <a href="index.php?page=Help&amp;item=search<?php echo SID_ARG_2ND; ?>">the help</a>.<?php } ?></p>
						</div>
					</div>
					
					<div class="formElement">
						<div class="formFieldLabel">
							<label for="searchAuthor">Search by author</label>
						</div>
						<div class="formField">
							<input type="text" class="inputText" id="searchAuthor" name="username" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" maxlength="255" />
							<script type="text/javascript">
								//<![CDATA[
								suggestion.setSource('index.php?page=PublicUserSuggest<?php echo SID_ARG_2ND_NOT_ENCODED; ?>');
								suggestion.enableMultiple(false);
								suggestion.init('searchAuthor');
								//]]>
							</script>
							<label><input type="checkbox" name="nameExactly" value="1"<?php if ($this->v['nameExactly']) { ?> checked="checked"<?php } ?> /> Exact match</label>
							<?php if (isset($this->v['additionalAuthorOptions'])) { ?><?php echo $this->v['additionalAuthorOptions']; ?><?php } ?> 
						</div>
					</div>
					
					<div class="formGroup">
						<div class="formGroupLabel">
							<label for="fromDay">In time period</label>
						</div>
						
						<div class="formGroupField">
							<fieldset id="searchPeriod">
							
								<legend><label for="fromDay">In time period</label></legend>
								
								<div class="floatedElement">
									<div class="floatedElement">
										<p> from:</p>
									</div>
									
									<div class="floatedElement">
										<label for="fromDay">Day</label>
										<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['dayOptions'], 'selected' => $this->v['fromDay'], 'id' => 'fromDay', 'name' => 'fromDay'), $this); ?>
									</div>
									
									<div class="floatedElement">
										<label for="fromMonth">Month</label>
										<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['monthOptions'], 'selected' => $this->v['fromMonth'], 'id' => 'fromMonth', 'name' => 'fromMonth'), $this); ?>
									</div>
									
									<div class="floatedElement">
										<label for="fromYear">Year</label>
										<input id="fromYear" class="inputText fourDigitInput" type="text" name="fromYear" value="<?php echo $this->v['fromYear']; ?>" maxlength="4" />
									</div>
									
									<div class="floatedElement">
										<a id="fromButton"><img src="<?php ob_start(); ?>datePickerOptionsM.png<?php $_icon06054ba29157ee4b9d41718b5742bfda0d67cdfd = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon06054ba29157ee4b9d41718b5742bfda0d67cdfd); ?>" alt="" /></a>
										<div id="fromCalendar" class="inlineCalendar"></div>
									</div>
								</div>
								
								<div class="floatedElement">
									<div class="floatedElement">
										<p> until:</p>
									</div>
									
									<div class="floatedElement">
										<label for="untilDay">Day</label>
										<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['dayOptions'], 'selected' => $this->v['untilDay'], 'id' => 'untilDay', 'name' => 'untilDay'), $this); ?>
									</div>
									
									<div class="floatedElement">
										<label for="untilMonth">Month</label>
										<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['monthOptions'], 'selected' => $this->v['untilMonth'], 'id' => 'untilMonth', 'name' => 'untilMonth'), $this); ?>
									</div>
									
									<div class="floatedElement">
										<label for="untilYear">Year</label>
										<input id="untilYear" class="inputText fourDigitInput" type="text" name="untilYear" value="<?php echo $this->v['untilYear']; ?>" maxlength="4" />
									</div>
									
									<div class="floatedElement">
										<a id="untilButton"><img src="<?php ob_start(); ?>datePickerOptionsM.png<?php $_icon4c8a8769939eab3c885922ad88e3c2c6dc25a12c = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon4c8a8769939eab3c885922ad88e3c2c6dc25a12c); ?>" alt="" /></a>
										<div id="untilCalendar" class="inlineCalendar"></div>
										<script type="text/javascript">
											//<![CDATA[
											calendar.init('from');
											calendar.init('until');
											//]]>
										</script>
									</div>
								</div>
								
							</fieldset>
						</div>
					</div>
					
					<div class="formGroup">
						<div class="formGroupLabel">
							<label for="sortField">Display</label>
						</div>
						<div class="formGroupField">
							<fieldset>
								<legend><label for="sortField">Display</label></legend>
								<div class="floatContainer">
									<div class="floatedElement">
										<label for="sortField">Sort by</label>
										<select id="sortField" name="sortField">
											<option value="relevance"<?php if ($this->v['sortField'] == 'relevance') { ?> selected="selected"<?php } ?>>Relevance</option>
											<option value="subject"<?php if ($this->v['sortField'] == 'subject') { ?> selected="selected"<?php } ?>>Subject</option>
											<option value="time"<?php if ($this->v['sortField'] == 'time') { ?> selected="selected"<?php } ?>>Date</option>
											<option value="username"<?php if ($this->v['sortField'] == 'username') { ?> selected="selected"<?php } ?>>Author</option>
										</select>
										
										<select name="sortOrder">
											<option value="ASC"<?php if ($this->v['sortOrder'] == 'ASC') { ?> selected="selected"<?php } ?>>ascending</option>
											<option value="DESC"<?php if ($this->v['sortOrder'] == 'DESC') { ?> selected="selected"<?php } ?>>descending</option>
										</select>
									</div>
									<?php if (isset($this->v['additionalDisplayOptions'])) { ?><?php echo $this->v['additionalDisplayOptions']; ?><?php } ?>
								</div>
							</fieldset>
						</div>
					</div>
					
					<div class="formGroup">
						<div class="formGroupLabel">
							Search in
						</div>
						<div class="formGroupField">
							<fieldset>
								<legend>Search in</legend>
								<div class="formField">
									<ul class="formOptions">
									<?php
if (count($this->v['types']) > 0) {
foreach ($this->v['types'] as $this->v['type'] => $this->v['typeObj']) {
?>
										<?php if ($this->v['typeObj']->isAccessible()) { ?>
											<li><label><input id="<?php echo StringUtil::encodeHTML($this->v['type']); ?>" type="checkbox" name="types[]" value="<?php echo StringUtil::encodeHTML($this->v['type']); ?>"<?php if (in_array($this->v['type'],$this->v['selectedTypes'])) { ?> checked="checked"<?php } ?> <?php if ($this->v['typeObj']->getFormTemplateName()) { ?>onclick="showSearchForm('<?php echo StringUtil::encodeHTML($this->v['type']); ?>Form', this.checked)" <?php } ?>/> <?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.search.type.<?php echo StringUtil::encodeHTML($this->v['type']); ?><?php $_lang4bb7d647dbd0ad3db223228d47ab83516c33e865 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang4bb7d647dbd0ad3db223228d47ab83516c33e865, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></label></li>
										<?php } ?>
									<?php } } ?>
									</ul>
								</div>
							</fieldset>
						</div>
					</div>
				</fieldset>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
				<?php
$outerTemplateNamef6300a06aeab01b920a175c96a3266649909ec79 = $this->v['tpl']['template'];
$this->includeTemplate('captcha', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef6300a06aeab01b920a175c96a3266649909ec79;
$this->v['tpl']['includedTemplates']['captcha'] = 1;
?>
				
				<?php
if (count($this->v['types']) > 0) {
foreach ($this->v['types'] as $this->v['type'] => $this->v['typeObj']) {
?>
					<?php if ($this->v['typeObj']->isAccessible() && $this->v['typeObj']->getFormTemplateName()) { ?>
						<fieldset id="<?php echo StringUtil::encodeHTML($this->v['type']); ?>Form">
							<legend><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.search.type.<?php echo StringUtil::encodeHTML($this->v['type']); ?><?php $_lang36129417c47a539b6f5161881269f245f8ac7e10 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang36129417c47a539b6f5161881269f245f8ac7e10, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></legend>
							
							<div><?php
$outerTemplateNamec83c7581e085f8ffed5e66efcee4297152cfef6d = $this->v['tpl']['template'];
$this->includeTemplate($this->v['typeObj']->getFormTemplateName(), array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamec83c7581e085f8ffed5e66efcee4297152cfef6d;
$this->v['tpl']['includedTemplates'][$this->v['typeObj']->getFormTemplateName()] = 1;
?></div>
						
							<?php if ( ! in_array($this->v['type'],$this->v['selectedTypes'])) { ?>
								<script type="text/javascript">
									//<![CDATA[
									showSearchForm('<?php echo StringUtil::encodeHTML($this->v['type']); ?>Form', false);
									//]]>
								</script>
							<?php } ?>
						</fieldset>
					<?php } ?>
				<?php } } ?>
			</div>
		</div>
		
		<div class="formSubmit">
			<input type="submit" accesskey="s" value="Submit" />
			<input type="reset" accesskey="r" value="Reset" />
			<?php echo SID_INPUT_TAG; ?>
		</div>
	</form>
	
	<?php if (isset($this->v['additionalBoxes2'])) { ?><?php echo $this->v['additionalBoxes2']; ?><?php } ?>

</div>

<?php
$outerTemplateNamede54e07359c422c2facd81368806c7bf4049a4be = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamede54e07359c422c2facd81368806c7bf4049a4be;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>