<?php
/**
* WoltLab Community Framework
* Template: index
* Compiled at: Fri, 30 Aug 2013 22:18:57 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'index';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
?><?php
$outerTemplateName387607be205ef3c79a86a206d327b3dff42988e9 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName387607be205ef3c79a86a206d327b3dff42988e9;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Main Page - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang8aa850585d6cc3eb00ca53e5ffe23bef02197f95 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang8aa850585d6cc3eb00ca53e5ffe23bef02197f95, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	
	<?php
$outerTemplateNamebbd06c213b3dae0b6515a67fd1e1983f14050fdc = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamebbd06c213b3dae0b6515a67fd1e1983f14050fdc;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateNamee864291d12fcd312c89a453e5fb278b66378a4de = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamee864291d12fcd312c89a453e5fb278b66378a4de;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<div class="mainHeadline">
		<img src="<?php ob_start(); ?>indexL.png<?php $_icon2af175279cf1aaa1254c95a2dec10a11f8bc318c = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon2af175279cf1aaa1254c95a2dec10a11f8bc318c); ?>" alt="" />
		<div class="headlineContainer">
			<h2><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang3230549ec75b569779daef44444d0ed1ad9f80e8 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang3230549ec75b569779daef44444d0ed1ad9f80e8, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h2>
			<p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_DESCRIPTION); ?><?php $_lang42eb66dde6a683c0c04f95539dee81410ba77d70 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang42eb66dde6a683c0c04f95539dee81410ba77d70, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if (isset($this->v['additionalTopContents'])) { ?><?php echo $this->v['additionalTopContents']; ?><?php } ?>
	
	<?php
$outerTemplateNamefb5cab48f0b3f71854258749c371f653d0c8df68 = $this->v['tpl']['template'];
$this->includeTemplate("boardList", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamefb5cab48f0b3f71854258749c371f653d0c8df68;
$this->v['tpl']['includedTemplates']["boardList"] = 1;
?>
	
	<?php if (INDEX_ENABLE_STATS || isset($this->v['additionalBoxes'])) { ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2', 'print' => false, 'advance' => false), $this); ?>
		<div class="border infoBox">
			<?php if (INDEX_ENABLE_STATS) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxStatistics">
					<div class="containerIcon"><img src="<?php ob_start(); ?>statisticsM.png<?php $_iconb73fe8829b0c5f3f1ab74edf1120c793829e4092 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconb73fe8829b0c5f3f1ab74edf1120c793829e4092); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Statistics:</h3> 
						<p class="smallFont"><?php echo StringUtil::formatNumeric($this->v['stats']['members']); ?> Member<?php if ($this->v['stats']['members'] != 1) { ?>s<?php } ?> - <?php echo StringUtil::formatNumeric($this->v['stats']['threads']); ?> <?php if ($this->v['stats']['threads'] == 1) { ?>Thread<?php } else { ?>Threads<?php } ?> - <?php echo StringUtil::formatNumeric($this->v['stats']['posts']); ?> <?php if ($this->v['stats']['posts'] == 1) { ?>Post<?php } else { ?>Posts<?php } ?> (<?php echo StringUtil::formatNumeric($this->v['stats']['postsPerDay']); ?> <?php if ($this->v['stats']['postsPerDay'] == 1) { ?>Post<?php } else { ?>Posts<?php } ?> per day)<br />
Newest member: <a href="index.php?page=User&amp;userID=<?php echo $this->v['stats']['newestMember']->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['stats']['newestMember']->username); ?></a>.</p>
					</div>
				</div>
			<?php } ?>
			
			<?php if (isset($this->v['additionalBoxes'])) { ?><?php echo $this->v['additionalBoxes']; ?><?php } ?>
		</div>
	<?php } ?>
	<div class="pageOptions">
		<?php if (isset($this->v['additionalPageOptions'])) { ?><?php echo $this->v['additionalPageOptions']; ?><?php } ?>
		<a href="index.php?action=BoardMarkAllAsRead&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php ob_start(); ?>boardMarkAsReadS.png<?php $_icon9a515cff894667706cd8e60e810aa0002437b895 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon9a515cff894667706cd8e60e810aa0002437b895); ?>" alt="" /> <span>Mark all Forums as read</span></a>
	</div>
</div>

<?php
$outerTemplateNamee9d521ffa6eefd0bbb382df5966269507aeaa693 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamee9d521ffa6eefd0bbb382df5966269507aeaa693;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>

</body>
</html>