<?php
/**
* WoltLab Community Framework
* Template: userListAdvancedUserOptions
* Compiled at: Fri, 30 Aug 2013 23:07:41 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userListAdvancedUserOptions';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><?php if ($this->v['this']->user->getPermission('admin.user.canEditPassword') && $this->v['this']->user->getPermission('admin.user.canMailUser')) { ?>
	// send new password
	count = additionalOptions.length;
	additionalOptions[count] = new Object();
	additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?action=UserSendNewPassword&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
	additionalOptions[count]['text'] = 'Send new password';
	additionalOptions[count]['className'] = 'bottomSeparator';
<?php } ?>

<?php if ($this->v['this']->user->getPermission('admin.user.canEnableUser')) { ?>
	// enable user
	count = additionalOptions.length;
	additionalOptions[count] = new Object();
	additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?action=UserEnable&url='+encodeURIComponent('<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['url']), $this); ?>')+'&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
	additionalOptions[count]['text'] = 'Enable';
	
	// disable user
	count = additionalOptions.length;
	additionalOptions[count] = new Object();
	additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?action=UserDisable&url='+encodeURIComponent('<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['url']), $this); ?>')+'&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
	additionalOptions[count]['text'] = 'Disable';
	
	<?php if (REGISTER_ACTIVATION_METHOD == 1) { ?>
		// send activation mail
		count = additionalOptions.length;
		additionalOptions[count] = new Object();
		additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?action=UserSendActivationMail&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
		additionalOptions[count]['text'] = 'Send activation e-mail';
	<?php } ?>
	
	additionalOptions[count]['className'] = 'bottomSeparator';
<?php } ?>

<?php if ($this->v['this']->user->getPermission('admin.user.canBanUser')) { ?>
	// ban user
	count = additionalOptions.length;
	additionalOptions[count] = new Object();
	additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?form=UserBan&url='+encodeURIComponent('<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['url']), $this); ?>')+'&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
	additionalOptions[count]['text'] = 'Ban';
	
	// undo ban
	count = additionalOptions.length;
	additionalOptions[count] = new Object();
	additionalOptions[count]['function'] = "document.location.href=fixURL('index.php?action=UserUnban&url='+encodeURIComponent('<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['url']), $this); ?>')+'&packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>')";
	additionalOptions[count]['text'] = 'Remove ban';
	additionalOptions[count]['className'] = 'bottomSeparator';
<?php } ?>