<?php
/**
* WoltLab Community Framework
* Template: userAdd
* Compiled at: Fri, 30 Aug 2013 23:07:50 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'userAdd';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmlcheckboxes'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmlcheckboxes.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmlcheckboxes'] = new TemplatePluginFunctionHtmlcheckboxes;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><?php
$outerTemplateNamecc677f7f498b894007f8418f487548119953a891 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamecc677f7f498b894007f8418f487548119953a891;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/TabMenu.class.js"></script>
<?php if (isset($this->v['userID'])) { ?>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/AjaxRequest.class.js"></script>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/InlineListEdit.class.js"></script>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>acp/js/UserListEdit.class.js"></script>
<?php } ?>
<script type="text/javascript">
	//<![CDATA[
	var tabMenu = new TabMenu();
	<?php if (count($this->v['options'])) { ?>onloadEvents.push(function() { tabMenu.showSubTabMenu('<?php echo $this->v['options'][0]['categoryName']; ?>') });<?php } ?>
	
	<?php if (isset($this->v['userID'])) { ?>
		var userData = new Hash();
		userData.set(<?php echo $this->v['userID']; ?>, {
			'isMarked': <?php echo $this->v['user']->isMarked(); ?>
		});
		
		var url = '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['url']), $this); ?>';
		
		// language
		var language = new Object();
		language['wcf.global.button.mark']		= 'Select';
		language['wcf.global.button.unmark']		= 'Unselect';
		language['wcf.global.button.delete']		= 'Delete';
		language['wcf.acp.user.button.sendMail']	= 'Send an e-mail';
		language['wcf.acp.user.button.exportMail']	= 'Export e-mail addresses';
		language['wcf.acp.user.button.assignGroup']	= 'Group assignment';
		language['wcf.acp.user.deleteMarked.sure']	= 'Are you sure that you would like to delete the selected User(s)?';
		language['wcf.acp.user.delete.sure']		= 'Are you sure that you would like to delete this user?';
		language['wcf.acp.user.markedUsers']		= 'this.count == 1 ? "1 user selected" : this.count+" users selected"';
		
		// additional options
		var additionalOptions = new Array();
		var additionalUserOptions = new Array();
		<?php if (isset($this->v['additionalUserOptions'])) { ?><?php echo $this->v['additionalUserOptions']; ?><?php } ?>
		<?php if (isset($this->v['additionalMarkedOptions'])) { ?><?php echo $this->v['additionalMarkedOptions']; ?><?php } ?>
		
		// permissions
		var permissions = new Object();
		permissions['canEditUser'] = <?php if ($this->v['this']->user->getPermission('admin.user.canEditUser')) { ?>1<?php } else { ?>0<?php } ?>;
		permissions['canDeleteUser'] = <?php if ($this->v['this']->user->getPermission('admin.user.canDeleteUser')) { ?>1<?php } else { ?>0<?php } ?>;
		permissions['canMailUser'] = <?php if ($this->v['this']->user->getPermission('admin.user.canMailUser')) { ?>1<?php } else { ?>0<?php } ?>;
		permissions['canEditMailAddress'] = <?php if ($this->v['this']->user->getPermission('admin.user.canEditMailAddress')) { ?>1<?php } else { ?>0<?php } ?>;
		permissions['canEditPassword'] = <?php if ($this->v['this']->user->getPermission('admin.user.canEditPassword')) { ?>1<?php } else { ?>0<?php } ?>;
		
		onloadEvents.push(function() { userListEdit = new UserListEdit(userData, <?php echo $this->v['markedUsers']; ?>, additionalUserOptions, additionalOptions); });
	<?php } ?>
	//]]>
</script>

<div class="mainHeadline">
	<img <?php if (isset($this->v['userID'])) { ?>id="userEdit<?php echo $this->v['userID']; ?>" <?php } ?>src="<?php echo RELATIVE_WCF_DIR; ?>icon/user<?php echo ucfirst($this->v['action']); ?>L.png" alt="" />
	<div class="headlineContainer">
		<h2><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.acp.user.<?php echo $this->v['action']; ?><?php $_lange955ffc98b6b4c54fe6f9b47e7eccd70616ac445 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lange955ffc98b6b4c54fe6f9b47e7eccd70616ac445, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h2>
	</div>
</div>

<?php if ($this->v['errorField']) { ?>
	<p class="error">The data you have entered are invalid. Please check the information you have given in the marked fields.</p>
<?php } ?>

<?php if (isset($this->v['success'])) { ?>
	<p class="success"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.acp.user.<?php echo $this->v['action']; ?>.success<?php $_langebb26baeef7aa611fc8c633b506e0b131f776a89 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langebb26baeef7aa611fc8c633b506e0b131f776a89, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>	
<?php } ?>

<?php if (isset($this->v['userID']) && $this->v['this']->user->userID == $this->v['userID']) { ?>
	<p class="warning">You are currently editing your own user account. Changing the permissions of this user group might lead to locking yourself out of the Administration Control Panel. Please be careful!</p>	
<?php } ?>

<div class="contentHeader">
	<div class="largeButtons">
		<ul>
			<li><a href="index.php?page=UserList&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>" title="List users"><img src="<?php echo RELATIVE_WCF_DIR; ?>icon/usersM.png" alt="" /> <span>List users</span></a></li>
			<li><a href="index.php?form=UserSearch&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>" title="Search for users"><img src="<?php echo RELATIVE_WCF_DIR; ?>icon/searchM.png" alt="" /> <span>Search for users</span></a></li>
			<?php if (isset($this->v['additionalLargeButtons'])) { ?><?php echo $this->v['additionalLargeButtons']; ?><?php } ?>
		</ul>
	</div>
</div>
<form method="post" action="index.php?form=User<?php echo ucfirst($this->v['action']); ?>">
	<div class="border content">
		<div class="container-1">
			<div class="formElement<?php if (isset($this->v['errorType']['username'])) { ?> formError<?php } ?>">
				<div class="formFieldLabel">
					<label for="username">Username</label>
				</div>
				<div class="formField">
					<input type="text" class="inputText" id="username" name="username" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" />
					<?php if (isset($this->v['errorType']['username'])) { ?>
						<p class="innerError">
							<?php if ($this->v['errorType']['username'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
							<?php if ($this->v['errorType']['username'] == 'notValid') { ?>The username you have entered is not valid.<?php } ?>
							<?php if ($this->v['errorType']['username'] == 'notUnique') { ?>The user name you have entered is already in use.<?php } ?>
						</p>
					<?php } ?>
				</div>
			</div>
			
			<?php if (count($this->v['availableGroups'])) { ?>
				<div class="formGroup">
					<div class="formGroupLabel">
						<label>Group memberships</label>
					</div>
					<div class="formGroupField">
						<fieldset>
							<legend>Group memberships</legend>
							
							<div class="formField">
								<?php echo $this->pluginObjects['TemplatePluginFunctionHtmlcheckboxes']->execute(array('options' => $this->v['availableGroups'], 'name' => 'groupIDs', 'selected' => $this->v['groupIDs']), $this); ?>
							</div>
						</fieldset>
					</div>
				</div>
			<?php } ?>
			
			<?php if ($this->v['action'] == 'add' || $this->v['this']->user->getPermission('admin.user.canEditMailAddress')) { ?>
				<fieldset>
					<legend>E-mail Address</legend>
					<div class="formElement<?php if (isset($this->v['errorType']['email'])) { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="email">E-mail Address</label>
						</div>
						<div class="formField">	
							<input type="text" class="inputText" id="email" name="email" value="<?php echo StringUtil::encodeHTML($this->v['email']); ?>" />
							<?php if (isset($this->v['errorType']['email'])) { ?>
								<p class="innerError">
									<?php if ($this->v['errorType']['email'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
									<?php if ($this->v['errorType']['email'] == 'notValid') { ?>The e-mail address you have entered is not valid.<?php } ?>
									<?php if ($this->v['errorType']['email'] == 'notUnique') { ?>The e-mail address you have entered has already been used by another user.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
					
					<div class="formElement<?php if (isset($this->v['errorType']['confirmEmail'])) { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="confirmEmail">Confirm E-mail Address</label>
						</div>
						<div class="formField">
							<input type="text" class="inputText" id="confirmEmail" name="confirmEmail" value="<?php echo StringUtil::encodeHTML($this->v['confirmEmail']); ?>" />
							<?php if (isset($this->v['errorType']['confirmEmail'])) { ?>
								<p class="innerError">
									<?php if ($this->v['errorType']['confirmEmail'] == 'notEqual') { ?>The given e-mail address and confirmation e-mail address are not identical.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
				</fieldset>
			<?php } ?>
			
			<?php if ($this->v['action'] == 'add' || $this->v['this']->user->getPermission('admin.user.canEditPassword')) { ?>
				<fieldset>
					<legend>Password</legend>
					<div class="formElement<?php if (isset($this->v['errorType']['password'])) { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="password">Password</label>
						</div>
						<div class="formField">
							<input type="password" class="inputText" id="password" name="password" value="<?php echo StringUtil::encodeHTML($this->v['password']); ?>" />
							<?php if (isset($this->v['errorType']['password'])) { ?>
								<p class="innerError">
									<?php if ($this->v['errorType']['password'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
					
					<div class="formElement<?php if (isset($this->v['errorType']['confirmPassword'])) { ?> formError<?php } ?>">
						<div class="formFieldLabel">
							<label for="confirmPassword">Confirm password</label>
						</div>
						<div class="formField">
							<input type="password" class="inputText" id="confirmPassword" name="confirmPassword" value="<?php echo StringUtil::encodeHTML($this->v['confirmPassword']); ?>" />
							<?php if (isset($this->v['errorType']['confirmPassword'])) { ?>
								<p class="innerError">
									<?php if ($this->v['errorType']['confirmPassword'] == 'notEqual') { ?>The given password and confirmation password are not identical.<?php } ?>
								</p>
							<?php } ?>
						</div>
					</div>
				</fieldset>
			<?php } ?>
		
			<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
			
			<?php if (count($this->v['options']) || isset($this->v['additionalTabs'])) { ?>
				<div class="tabMenu">
					<ul>
						<?php
if (count($this->v['options']) > 0) {
foreach ($this->v['options'] as $this->v['categoryLevel1']) {
?>
							<li id="<?php echo $this->v['categoryLevel1']['categoryName']; ?>"><a onclick="tabMenu.showSubTabMenu('<?php echo $this->v['categoryLevel1']['categoryName']; ?>');"><span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo $this->v['categoryLevel1']['categoryName']; ?><?php $_langd396c21f2e4463f32d5ad8124bdc2722c2d8f4fb = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langd396c21f2e4463f32d5ad8124bdc2722c2d8f4fb, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a></li>
						<?php } } ?>
						
						<?php if (isset($this->v['additionalTabs'])) { ?><?php echo $this->v['additionalTabs']; ?><?php } ?>
					</ul>
				</div>
				<div class="subTabMenu">
					<div class="containerHead"><div> </div></div>
				</div>
				
				<?php
if (count($this->v['options']) > 0) {
foreach ($this->v['options'] as $this->v['categoryLevel1']) {
?>
					<div class="border tabMenuContent hidden" id="<?php echo $this->v['categoryLevel1']['categoryName']; ?>-content">
						<div class="container-1">
							<h3 class="subHeadline"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo $this->v['categoryLevel1']['categoryName']; ?><?php $_lang83e67036ff528ae3dd5c2c359fd1eb0aff59d804 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang83e67036ff528ae3dd5c2c359fd1eb0aff59d804, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h3>
							
							<?php
if (count($this->v['categoryLevel1']['categories']) > 0) {
foreach ($this->v['categoryLevel1']['categories'] as $this->v['categoryLevel2']) {
?>
								<fieldset>
									<legend><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wcf.user.option.category.<?php echo $this->v['categoryLevel2']['categoryName']; ?><?php $_lang02d7f74640f0119fdc5b56a560378e2824ddebb9 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang02d7f74640f0119fdc5b56a560378e2824ddebb9, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></legend>
									
									<?php if ($this->v['categoryLevel2']['categoryName'] == 'settings.general' && count($this->v['availableLanguages']) > 1) { ?>
										<div class="formElement">
											<div class="formFieldLabel">
												<label for="languageID">Language</label>
											</div>
											<div class="formField">
												<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['availableLanguages'], 'selected' => $this->v['languageID'], 'name' => 'languageID', 'id' => 'languageID', 'disableEncoding' => true), $this); ?>
											</div>
										</div>
											
										<?php if (count($this->v['availableContentLanguages']) > 1) { ?>
											<div class="formGroup">
												<div class="formGroupLabel">
													Show content in the following languages
												</div>
												<div class="formGroupField">
													<fieldset>
														<legend>Show content in the following languages</legend>
														<div class="formField">
															<ul class="formOptions">
															<?php
if (count($this->v['availableContentLanguages']) > 0) {
foreach ($this->v['availableContentLanguages'] as $this->v['availableLanguageID'] => $this->v['availableLanguage']) {
?>
																<li><label><input type="checkbox" name="visibleLanguages[]" value="<?php echo $this->v['availableLanguageID']; ?>"<?php if (in_array($this->v['availableLanguageID'],$this->v['visibleLanguages'])) { ?> checked="checked"<?php } ?> /> <?php echo $this->v['availableLanguage']; ?></label></li>
															<?php } } ?>
															</ul>
														</div>
													</fieldset>
												</div>
											</div>
										<?php } ?>
									<?php } ?>
									
									<?php
$outerTemplateName8feda9a2c91ab296e5ca58bdd0e2888e0404f3f0 = $this->v['tpl']['template'];
$this->includeTemplate('optionFieldList', array('options' => $this->v['categoryLevel2']['options'], 'langPrefix' => 'wcf.user.option.'), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName8feda9a2c91ab296e5ca58bdd0e2888e0404f3f0;
$this->v['tpl']['includedTemplates']['optionFieldList'] = 1;
?>
								</fieldset>
							<?php } } ?>
						</div>
					</div>
				<?php } } ?>
			<?php } ?>
			
			<?php if (isset($this->v['additionalTabContents'])) { ?><?php echo $this->v['additionalTabContents']; ?><?php } ?>
		</div>
	</div>
	
	<div class="formSubmit">
		<input type="submit" accesskey="s" value="Submit" />
		<input type="reset" accesskey="r" value="Reset" />
		<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
 		<?php echo SID_INPUT_TAG; ?>
 		<input type="hidden" name="action" value="<?php echo $this->v['action']; ?>" />
 		<?php if (isset($this->v['userID'])) { ?><input type="hidden" name="userID" value="<?php echo $this->v['userID']; ?>" /><?php } ?>
 	</div>
</form>

<?php
$outerTemplateName2478f6ea22ff0fa2e7e663fb039779bd62dd20c4 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2478f6ea22ff0fa2e7e663fb039779bd62dd20c4;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>