<?php
/**
* WoltLab Community Framework
* Template: index
* Compiled at: Fri, 30 Aug 2013 22:18:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'index';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginModifierTime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierTime.class.php');
$this->pluginObjects['TemplatePluginModifierTime'] = new TemplatePluginModifierTime;
}
if (!isset($this->pluginObjects['TemplatePluginModifierFilesize'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierFilesize.class.php');
$this->pluginObjects['TemplatePluginModifierFilesize'] = new TemplatePluginModifierFilesize;
}
?><?php
$outerTemplateName3f8c1909f9afb22f3d43a1fdd94c75c254e8ca1d = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3f8c1909f9afb22f3d43a1fdd94c75c254e8ca1d;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/Suggestion.class.js"></script>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/TabMenu.class.js"></script>
<script type="text/javascript">
	//<![CDATA[
	var tabMenu = new TabMenu();
	onloadEvents.push(function() { tabMenu.showSubTabMenu('<?php if (count($this->v['updates']) > 0) { ?>updates<?php } elseif (count($this->v['news']) > 0) { ?>news<?php } else { ?>system<?php } ?>') });
	//]]>
</script>

<div class="mainHeadline">
	<img src="<?php echo RELATIVE_WCF_DIR; ?>icon/acpL.png" alt="" />
	<div class="headlineContainer">
		<h2>WoltLab&reg; Burning Board&reg; Lite Administration Control Panel</h2>
	</div>
</div>



<?php if ($this->v['this']->user->getPermission('admin.user.canEditUser')) { ?>
	<form method="post" action="index.php?form=UserSearch">
		<fieldset>
			<legend>Quick search for users</legend>
			
			<div class="formElement">
				<div class="formFieldLabel">
					<label for="username">Username</label>
				</div>
				<div class="formField">
					<input type="text" class="inputText" id="username" name="staticParameters[username]" value="" />
					<script type="text/javascript">
						//<![CDATA[
						suggestion.enableMultiple(false);
						suggestion.init('username');
						//]]>
					</script>
					<label><input type="checkbox" name="matchExactly[username]" value="1" /> Exact match</label>
				</div>
			</div>
			
			<?php if ($this->v['this']->user->getPermission('admin.user.canMailUser')) { ?>
				<div class="formElement">
					<div class="formFieldLabel">
						<label for="email">E-mail Address</label>
					</div>
					<div class="formField">	
						<input type="text" class="inputText" id="email" name="staticParameters[email]" value="" />
						<label><input type="checkbox" name="matchExactly[email]" value="1" /> Exact match</label>
					</div>
				</div>
			<?php } ?>
			
			<?php if (isset($this->v['additionalSearchFields'])) { ?><?php echo $this->v['additionalSearchFields']; ?><?php } ?>
		</fieldset>
		<div class="formSubmit">
			<input type="submit" accesskey="s" value="Submit" />
			<input type="reset" accesskey="r" value="Reset" />
			<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
	 		<?php echo SID_INPUT_TAG; ?>
		</div>
	</form>
<?php } ?>

<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>

<div class="tabMenu">
	<ul>
		<?php if (count($this->v['updates']) > 0) { ?><li id="updates"><a onclick="tabMenu.showSubTabMenu('updates');"><span>Updates</span></a></li><?php } ?>
		<?php if (count($this->v['news']) > 0) { ?><li id="news"><a onclick="tabMenu.showSubTabMenu('news');"><span>News</span></a></li><?php } ?>
		<li id="system"><a onclick="tabMenu.showSubTabMenu('system');"><span>System</span></a></li>
		<li id="stat"><a onclick="tabMenu.showSubTabMenu('stat');"><span>Statistics</span></a></li>
		<li id="credits"><a onclick="tabMenu.showSubTabMenu('credits');"><span>About WoltLab&reg; Burning Board&reg; Lite</span></a></li>
		<?php if (isset($this->v['additionalTabs'])) { ?><?php echo $this->v['additionalTabs']; ?><?php } ?>
	</ul>
</div>
<div class="subTabMenu">
	<div class="containerHead"><div> </div></div>
</div>

<?php if (count($this->v['updates']) > 0) { ?>
	<form method="post" action="index.php?form=PackageUpdate">
		<div class="border tabMenuContent hidden" id="updates-content">
			<div class="container-1">
				<h3 class="subHeadline">Updates</h3>
				<p class="description">The following updates are currently available.</p>
				
				<ul>
					<?php
if (count($this->v['updates']) > 0) {
foreach ($this->v['updates'] as $this->v['update']) {
?>
						<li<?php if ($this->v['update']['version']['updateType'] == 'security') { ?> class="formError"<?php } ?>>
							<?php echo StringUtil::encodeHTML($this->v['update']['packageName']); ?><?php if ($this->v['update']['instanceNo'] > 1) { ?> (#<?php echo StringUtil::encodeHTML($this->v['update']['instanceNo']); ?>)<?php } ?> Version <?php echo StringUtil::encodeHTML($this->v['update']['version']['packageVersion']); ?>
							<input type="hidden" name="updates[<?php echo $this->v['update']['packageID']; ?>]" value="<?php echo StringUtil::encodeHTML($this->v['update']['version']['packageVersion']); ?>" />
						</li>
					<?php } } ?>
				</ul>
				
				<p><input type="submit" value="Start Update" /></p>
				<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
				<?php echo SID_INPUT_TAG; ?>
			</div>
		</div>
	</form>
<?php } ?>

<?php if (count($this->v['news']) > 0) { ?>
	<div class="border tabMenuContent hidden" id="news-content">
		<div class="container-1">
			<h3 class="subHeadline">News</h3>
			
			<?php
if (count($this->v['news']) > 0) {
foreach ($this->v['news'] as $this->v['newsItem']) {
?>
				
				<div class="message content">
					<div class="messageInner container-<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('name' => 'results', 'values' => '1,2'), $this); ?>">
						<p class="light smallFont"><?php if ($this->v['newsItem']['author']) { ?><?php echo StringUtil::encodeHTML($this->v['newsItem']['author']); ?> - <?php } ?><?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array($this->v['newsItem']['pubDate']), $this); ?></p>
						<h4><a href="<?php echo RELATIVE_WCF_DIR; ?>acp/dereferrer.php?url=<?php echo StringUtil::encodeHTML(rawurlencode($this->v['newsItem']['link'])); ?>" class="externalURL"><?php echo $this->v['newsItem']['title']; ?></a></h4>

						<div class="messageBody">
							<?php echo $this->v['newsItem']['description']; ?>
						</div>
						<hr />
					</div>
				</div>
			<?php } } ?>
		</div>
	</div>
<?php } ?>

<div class="border tabMenuContent hidden" id="system-content">
	<div class="container-1">
		<h3 class="subHeadline">System</h3>
		
		<fieldset>
			<legend>Software</legend>
		
			<div class="formElement">
				<p class="formFieldLabel">Burning Board&reg; Lite Version</p>
				<p class="formField"><?php echo StringUtil::encodeHTML(PACKAGE_VERSION); ?> (Aurora)</p>
			</div>
			<div class="formElement">
				<p class="formFieldLabel">Installation date</p>
				<p class="formField"><?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array(INSTALL_DATE), $this); ?></p>
			</div>
			<div class="formElement">
				<p class="formFieldLabel">Community Framework&trade; Version</p>
				<p class="formField"><?php echo StringUtil::encodeHTML(WCF_VERSION); ?></p>
			</div>
		</fieldset>
		
		<fieldset>
			<legend>Server</legend>
		
			<div class="formElement">
				<p class="formFieldLabel">Operating System</p>
				<p class="formField"><?php echo StringUtil::encodeHTML($this->v['os']); ?></p>
			</div>
			<div class="formElement">
				<p class="formFieldLabel">Webserver</p>
				<p class="formField"><?php echo StringUtil::encodeHTML($this->v['webserver']); ?></p>
			</div>
			<div class="formElement">
				<p class="formFieldLabel">PHP Version</p>
				<p class="formField"><?php echo StringUtil::encodeHTML(PHP_VERSION); ?></p>
			</div>
			<div class="formElement">
				<p class="formFieldLabel">Database Type</p>
				<p class="formField"><?php echo StringUtil::encodeHTML($this->v['sqlType']); ?> &quot;<?php echo StringUtil::encodeHTML($this->v['dbName']); ?>&quot;</p>
			</div>
			<div class="formElement">
				<p class="formFieldLabel">MySQL Version</p>
				<p class="formField"><?php echo StringUtil::encodeHTML($this->v['sqlVersion']); ?></p>
			</div>
			<?php if ($this->v['load']) { ?>
				<div class="formElement">
					<p class="formFieldLabel">Current UNIX Load</p>
					<p class="formField"><?php echo StringUtil::encodeHTML($this->v['load']); ?></p>
				</div>
			<?php } ?>
		</fieldset>
		
		<form method="get" action="index.php">
			<div class="formSubmit">
				<button type="submit"><img src="<?php echo RELATIVE_WCF_DIR; ?>icon/saveS.png" alt="" /> Download system information</button>
				<input type="hidden" name="action" value="SystemInformationXMLExport" />
				<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
				<?php echo SID_INPUT_TAG; ?>
			</div>
		</form>
	</div>
</div>

<div class="border tabMenuContent hidden" id="stat-content">
	<div class="container-1">
		<h3 class="subHeadline">Statistics</h3>
		
		<div class="formElement">
			<p class="formFieldLabel">Members</p>
			<p class="formField"><?php echo StringUtil::formatNumeric($this->v['members']); ?></p>
		</div>
		<div class="formElement">
			<p class="formFieldLabel">Threads</p>
			<p class="formField"><?php echo StringUtil::formatNumeric($this->v['threads']); ?> (<?php echo StringUtil::formatNumeric($this->v['threadsPerDay']); ?> Threads per day)</p>
		</div>
		<div class="formElement">
			<p class="formFieldLabel">Posts</p>
			<p class="formField"><?php echo StringUtil::formatNumeric($this->v['posts']); ?> (<?php echo StringUtil::formatNumeric($this->v['postsPerDay']); ?> Posts per day)</p>
		</div>
		<div class="formElement">
			<p class="formFieldLabel">Database entries</p>
			<p class="formField"><?php echo StringUtil::formatNumeric($this->v['databaseEntries']); ?></p>
		</div>
		<div class="formElement">
			<p class="formFieldLabel">Database size</p>
			<p class="formField"><?php echo $this->pluginObjects['TemplatePluginModifierFilesize']->execute(array($this->v['databaseSize']), $this); ?></p>
		</div>
	</div>
</div>

<div class="border tabMenuContent hidden" id="credits-content">
	<div class="container-1">
		<h3 class="subHeadline">About WoltLab&reg; Burning Board&reg; Lite</h3>
		
		<div class="formElement">
			<p class="formFieldLabel">Software developed by</p>
			<p class="formField"><a href="<?php echo RELATIVE_WCF_DIR; ?>acp/dereferrer.php?url=<?php echo StringUtil::encodeHTML(rawurlencode("http://www.woltlab.com")); ?>" class="externalURL">WoltLab&reg; GmbH</a></p>
		</div>
		
		<div class="formElement">
			<p class="formFieldLabel">Project management</p>
			<p class="formField">Marcel Werk</p>
		</div>
		
		<div class="formElement">
			<p class="formFieldLabel">Development</p>
			<p class="formField">Alexander Ebert, Benjamin Kunz, Michael Sch&auml;fer, Siegfried Schweizer, Troublegum, Marcel Werk</p>
		</div>
		
		<div class="formElement">
			<p class="formFieldLabel">Design</p>
			<p class="formField">Arian Glander, Harald Szekely, Marcel Werk</p>
		</div>
		
		<div class="formElement">
			<p class="formFieldLabel">Contributor</p>
			<p class="formField">Yari Alsleben, Thorsten Buitkamp, Jonathan Hald, Frederic Schneider</p>
		</div>
		
		<div class="formElement">
			<p class="formFieldLabel">Translation</p>
			<p class="formField">Dean Baric (hr), Ingmar J&oslash;rgensen (da), Evandro Meneses (pt-BR), Paulo Henrique Lima (pt-BR), Pedro Henrique Barboza (pt-BR), Guillaume Perucha (fr), Giovanni Angelo Pinna (it), J&ouml;rgen Sj&ouml;holm (sv), Hui Wang (zh), Umut Yilmaz (tr)</p>
		</div>
		
		<div class="formElement" style="margin-top: 10px">
			<p class="formFieldLabel"></p>
			<p class="formField">Copyright &copy; 2001-2010 WoltLab&reg; GmbH. All rights reserved.</p>
		</div>
		
		<div class="formElement">
			<p class="formFieldLabel"></p>
			<p class="formField">&quot;WoltLab&reg;&quot; and &quot;Burning Board&reg;&quot; are registered Community Trade Marks at The Office of Harmonization for the Internal Market (OHIM) in Alicante, Spain.</p>
		</div>
	</div>
</div>

<?php if (isset($this->v['additionalTabContents'])) { ?><?php echo $this->v['additionalTabContents']; ?><?php } ?>

<?php
$outerTemplateNamea7a3d786018f81eb2a89bb512a460eebc458b6e9 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamea7a3d786018f81eb2a89bb512a460eebc458b6e9;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>