<?php
/**
* WoltLab Community Framework
* Template: boardAdd
* Compiled at: Fri, 30 Aug 2013 23:11:59 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'boardAdd';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><?php
$outerTemplateNamea5e37504141d2d1d5c6c4341546e4c60efb8bb76 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamea5e37504141d2d1d5c6c4341546e4c60efb8bb76;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<?php if ($this->v['action'] == 'add') { ?><?php $this->assign('dataPermission', "admin.board.canAddBoard"); ?>
<?php } else { ?><?php $this->assign('dataPermission', "admin.board.canEditBoard"); ?>
<?php } ?>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/Suggestion.class.js"></script>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/TabMenu.class.js"></script>
<script type="text/javascript">
	//<![CDATA[
	var tabMenu = new TabMenu();
	onloadEvents.push(function() { tabMenu.showSubTabMenu("<?php echo StringUtil::encodeHTML($this->v['activeTabMenuItem']); ?>") });
	//]]>
</script>

<div class="mainHeadline">
	<img src="<?php echo RELATIVE_WBB_DIR; ?>icon/board<?php echo ucfirst($this->v['action']); ?>L.png" alt="" />
	<div class="headlineContainer">
		<h2><?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wbb.acp.board.<?php echo $this->v['action']; ?><?php $_lang0d1ce0da2c68e32d5862f484dc83884ab617bef7 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang0d1ce0da2c68e32d5862f484dc83884ab617bef7, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h2>
		<?php if (isset($this->v['boardID'])) { ?><p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_lang01c46eea7d9cab5436e34bbdd8072df0c2fff745 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang01c46eea7d9cab5436e34bbdd8072df0c2fff745, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p><?php } ?>
	</div>
</div>

<?php if ($this->v['errorField']) { ?>
	<p class="error">The data you have entered are invalid. Please check the information you have given in the marked fields.</p>
<?php } ?>

<?php if (isset($this->v['success'])) { ?>
	<p class="success"><?php if ($this->v['action'] == 'add') { ?>The new forum has been saved successfully.<?php } else { ?>Your changes have been saved successfully.<?php } ?></p>
<?php } ?>

<script type="text/javascript" src="<?php echo RELATIVE_WBB_DIR; ?>acp/js/PermissionList.class.js"></script>
<script type="text/javascript">
	//<![CDATA[
	var language = new Object();
	
	
	// static
	language['wbb.acp.board.permissions.permissionsFor'] = 'Permissions for {$name}';
	language['wbb.acp.board.permissions.fullControl'] = 'Full control';
	
	
	// dynamic
	<?php
if (count($this->v['permissionSettings']) > 0) {
foreach ($this->v['permissionSettings'] as $this->v['permissionSetting']) {
?>
		language['wbb.acp.board.permissions.<?php echo $this->v['permissionSetting']; ?>'] = '<?php $this->tagStack[] = array('lang', array()); ob_start(); ?>wbb.acp.board.permissions.<?php echo $this->v['permissionSetting']; ?><?php $_lang705aa44896d8b2fbe35d3a6dffc9d64ec9803b7c = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang705aa44896d8b2fbe35d3a6dffc9d64ec9803b7c, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>';
	<?php } } ?>
	
	function setBoardType(newType) {
		switch (newType) {
			case 0:
				showOptions('filter', 'settings');
				break;
			case 1:
				hideOptions('filter', 'settings');
				break;
		}
	}
	onloadEvents.push(function() { setBoardType(<?php echo $this->v['boardType']; ?>); });

	var permissions = new Array();
	<?php $this->assign('i', 0); ?>
	<?php
if (count($this->v['permissions']) > 0) {
foreach ($this->v['permissions'] as $this->v['permission']) {
?>
		permissions[<?php echo $this->v['i']; ?>] = new Object();
		permissions[<?php echo $this->v['i']; ?>]['name'] = '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['permission']['name']), $this); ?>';
		permissions[<?php echo $this->v['i']; ?>]['type'] = '<?php echo $this->v['permission']['type']; ?>';
		permissions[<?php echo $this->v['i']; ?>]['id'] = '<?php echo $this->v['permission']['id']; ?>';
		permissions[<?php echo $this->v['i']; ?>]['settings'] = new Object();
		permissions[<?php echo $this->v['i']; ?>]['settings']['fullControl'] = -1;

		<?php
if (count($this->v['permission']['settings']) > 0) {
foreach ($this->v['permission']['settings'] as $this->v['setting'] => $this->v['value']) {
?>
			<?php if ($this->v['setting'] != 'name' && $this->v['setting'] != 'type' && $this->v['setting'] != 'id') { ?>
				permissions[<?php echo $this->v['i']; ?>]['settings']['<?php echo $this->v['setting']; ?>'] = <?php echo $this->v['value']; ?>;
			<?php } ?>
		<?php } } ?>
		<?php $this->assign('i', $this->v['i']+1); ?>
	<?php } } ?>

	var permissionSettings = new Array(<?php
$_lengthe9eb0d1b401844417186413a28b753b62e18b8ea = count($this->v['permissionSettings']);
$_ie9eb0d1b401844417186413a28b753b62e18b8ea = 0;
foreach ($this->v['permissionSettings'] as $this->v['permissionSetting']) { ?>'<?php echo $this->v['permissionSetting']; ?>'<?php
if (++$_ie9eb0d1b401844417186413a28b753b62e18b8ea < $_lengthe9eb0d1b401844417186413a28b753b62e18b8ea) { echo ', '; }
} ?>);

	onloadEvents.push(function() {
		// user/group permissions
		var list2 = new PermissionList('permission', permissions, permissionSettings);
		// add onsubmit event
		document.forms[0].onsubmit = function() {
			if (suggestion.selectedIndex != -1) return false;
			if (list2.inputHasFocus) return false;
			list2.submit(this);
		};
	});

	//]]>
</script>
<div class="contentHeader">
	<div class="largeButtons">
		<ul><li><a href="index.php?page=BoardList&amp;packageID=<?php echo PACKAGE_ID; ?><?php echo SID_ARG_2ND; ?>" title="Show forums"><img src="<?php echo RELATIVE_WBB_DIR; ?>icon/boardM.png" alt="" /> <span>Show forums</span></a></li></ul>
	</div>
</div>
<form method="post" action="index.php?form=Board<?php echo ucfirst($this->v['action']); ?>">
	<div class="border content">
		<div class="container-1">
			<?php if ($this->v['this']->user->getPermission($this->v['dataPermission'])) { ?>
				<fieldset>
					<legend>Type of forum</legend>
					<div class="formElement<?php if ($this->v['errorField'] == 'boardType') { ?> formError<?php } ?>">
						<ul class="formOptions">
							<li><label><input onclick="if (IS_SAFARI) setBoardType(0)" onfocus="setBoardType(0)" type="radio" name="boardType" value="0" <?php if ($this->v['boardType'] == 0) { ?>checked="checked" <?php } ?>/> Forum</label></li>
							<li><label><input onclick="if (IS_SAFARI) setBoardType(1)" onfocus="setBoardType(1)" type="radio" name="boardType" value="1" <?php if ($this->v['boardType'] == 1) { ?>checked="checked" <?php } ?>/> Category</label></li>
						</ul>
						<?php if ($this->v['errorField'] == 'boardType') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'invalid') { ?>wbb.acp.board.error.boardType.invalid<?php } ?>
							</p>
						<?php } ?>
					</div>
				</fieldset>
			<?php } ?>

			<div class="tabMenu">
				<ul>
					<?php if ($this->v['this']->user->getPermission($this->v['dataPermission'])) { ?><li id="data"><a onclick="tabMenu.showSubTabMenu('data');"><span>Data</span></a></li><?php } ?>
					<?php if ($this->v['this']->user->getPermission('admin.board.canEditPermissions')) { ?><li id="permissions"><a onclick="tabMenu.showSubTabMenu('permissions');"><span>Permissions for users and groups</span></a></li><?php } ?>
					<?php if (isset($this->v['additionalTabs'])) { ?><?php echo $this->v['additionalTabs']; ?><?php } ?>
				</ul>
			</div>
			<div class="subTabMenu">
				<div class="containerHead"><div> </div></div>
			</div>

			<?php if ($this->v['this']->user->getPermission($this->v['dataPermission'])) { ?>
				<div class="border tabMenuContent hidden" id="data-content">
					<div class="container-1">
						<h3 class="subHeadline">Data</h3>

						<fieldset>
							<legend>General Data</legend>
							<div class="formElement<?php if ($this->v['errorField'] == 'title') { ?> formError<?php } ?>">
								<div class="formFieldLabel">
									<label for="title">Title</label>
								</div>
								<div class="formField">
									<input type="text" class="inputText" id="title" name="title" value="<?php echo StringUtil::encodeHTML($this->v['title']); ?>" />
									<?php if ($this->v['errorField'] == 'title') { ?>
										<p class="innerError">
											<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
										</p>
									<?php } ?>
								</div>
							</div>

							<div id="descriptionDiv" class="formElement">
								<div class="formFieldLabel">
									<label for="description">Description</label>
								</div>
								<div class="formField">
									<textarea id="description" name="description" cols="40" rows="10"><?php echo StringUtil::encodeHTML($this->v['description']); ?></textarea>
									<label><input type="checkbox" name="allowDescriptionHtml" value="1" <?php if ($this->v['allowDescriptionHtml']) { ?>checked="checked" <?php } ?>/> Use HTML code in description</label>
								</div>
							</div>
						</fieldset>

						<fieldset>
							<legend>Position of forum</legend>

							<?php if (count($this->v['boardOptions']) > 0) { ?>
								<div class="formElement<?php if ($this->v['errorField'] == 'parentID') { ?> formError<?php } ?>" id="parentIDDiv">
									<div class="formFieldLabel">
										<label for="parentID">Parent Forum</label>
									</div>
									<div class="formField">
										<select name="parentID" id="parentID">
											<option value="0"></option>
											<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['boardOptions'], 'disableEncoding' => true, 'selected' => $this->v['parentID']), $this); ?>
										</select>
										<?php if ($this->v['errorField'] == 'parentID') { ?>
											<p class="innerError">
												<?php if ($this->v['errorType'] == 'invalid') { ?>wbb.acp.board.error.parentID.invalid<?php } ?>
											</p>
										<?php } ?>
									</div>
									<div class="formFieldDesc hidden" id="parentIDHelpMessage">
										Please select the parent forum.
									</div>
								</div>
								<script type="text/javascript">//<![CDATA[
									inlineHelp.register('parentID');
								//]]></script>
							<?php } ?>

							<div class="formElement<?php if ($this->v['errorField'] == 'position') { ?> formError<?php } ?>" id="positionDiv">
								<div class="formFieldLabel">
									<label for="position">Position number</label>
								</div>
								<div class="formField">
									<input type="text" class="inputText" id="position" name="position" value="<?php echo $this->v['position']; ?>" />
									<?php if ($this->v['errorField'] == 'position') { ?>
										<p class="innerError">
											<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
										</p>
									<?php } ?>
								</div>
								<div class="formFieldDesc hidden" id="positionHelpMessage">
									Please enter the position number of this forum. The forums are sorted according to these numbers.
								</div>
							</div>
							<script type="text/javascript">//<![CDATA[
								inlineHelp.register('position');
							//]]></script>

							<div class="formElement" id="invisibleDiv">
								<div class="formField">
									<label id="invisible"><input type="checkbox" name="invisible" value="1" <?php if ($this->v['invisible']) { ?>checked="checked" <?php } ?>/> Hide forum from all users.</label>
								</div>
								<div class="formFieldDesc hidden" id="invisibleHelpMessage">
									You can hide this forum on the forums list. It can only be accessed via a direct link.
								</div>
							</div>
							<script type="text/javascript">//<![CDATA[
								inlineHelp.register('invisible');
							//]]></script>
						</fieldset>

						<fieldset id="settings">
							<legend>Settings</legend>
							<div>
								<div class="formElement">
									<div class="formField">
										<label id="closed"><input type="checkbox" name="closed" value="1" <?php if ($this->v['closed']) { ?>checked="checked" <?php } ?>/> Archive (Forum closed for new posts)</label>
									</div>
								</div>

								<div class="formElement">
									<div class="formField">
										<label id="countUserPosts"><input type="checkbox" name="countUserPosts" value="1" <?php if ($this->v['countUserPosts']) { ?>checked="checked" <?php } ?>/> Count posts as users' posts of this forum</label>
									</div>
								</div>
							</div>

							<?php if (isset($this->v['additionalSettings'])) { ?><?php echo $this->v['additionalSettings']; ?><?php } ?>
						</fieldset>

						<fieldset id="filter">
							<legend>Filter and sorting options</legend>
							<div class="formElement<?php if ($this->v['errorField'] == 'sortField') { ?> formError<?php } ?>">
								<div class="formFieldLabel">
									<label for="sortField">Sorting of threads</label>
								</div>
								<div class="formField">
									<select name="sortField" id="sortField">
										<option value=""></option>
										<option value="topic"<?php if ($this->v['sortField'] == 'topic') { ?> selected="selected"<?php } ?>>Topic</option>
										<option value="username"<?php if ($this->v['sortField'] == 'starter') { ?> selected="selected"<?php } ?>>Author</option>
										<option value="time"<?php if ($this->v['sortField'] == 'startTime') { ?> selected="selected"<?php } ?>>First post</option>
										<option value="replies"<?php if ($this->v['sortField'] == 'replies') { ?> selected="selected"<?php } ?>>Replies</option>
										<option value="views"<?php if ($this->v['sortField'] == 'views') { ?> selected="selected"<?php } ?>>Views</option>
										<option value="lastPostTime"<?php if ($this->v['sortField'] == 'lastPostTime') { ?> selected="selected"<?php } ?>>Latest post</option>
									</select>
									<?php if ($this->v['errorField'] == 'sortField') { ?>
										<p class="innerError">
											<?php if ($this->v['errorType'] == 'invalid') { ?>wbb.acp.board.error.sortField.invalid<?php } ?>
										</p>
									<?php } ?>
								</div>
							</div>

							<div class="formElement<?php if ($this->v['errorField'] == 'sortOrder') { ?> formError<?php } ?>">
								<div class="formFieldLabel">
									<label for="sortOrder">Sort order of threads</label>
								</div>
								<div class="formField">
									<select name="sortOrder" id="sortOrder">
										<option value=""></option>
										<option value="ASC"<?php if ($this->v['sortOrder'] == 'ASC') { ?> selected="selected"<?php } ?>>ascending</option>
										<option value="DESC"<?php if ($this->v['sortOrder'] == 'DESC') { ?> selected="selected"<?php } ?>>descending</option>
									</select>
									<?php if ($this->v['errorField'] == 'sortField') { ?>
										<p class="innerError">
											<?php if ($this->v['errorType'] == 'invalid') { ?>wbb.acp.board.error.sortField.invalid<?php } ?>
										</p>
									<?php } ?>
								</div>
							</div>
						</fieldset>

						<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
					</div>
				</div>
			<?php } ?>

			<?php if ($this->v['this']->user->getPermission('admin.board.canEditPermissions')) { ?>
				<div class="border tabMenuContent hidden" id="permissions-content">
					<div class="container-1">
						<h3 class="subHeadline">Permissions for users and groups</h3>
				
						<div class="formElement">
							<div class="formFieldLabel" id="permissionTitle">
								Group and usernames
							</div>
							<div class="formField"><div id="permission" class="accessRights container-4"></div></div>
						</div>
						<div class="formElement">
							<div class="formField">	
								<input id="permissionAddInput" type="text" name="" value="" class="inputText accessRightsInput" />
								<script type="text/javascript">
									//<![CDATA[
									suggestion.setSource('index.php?page=BoardPermissionsObjectsSuggest<?php echo SID_ARG_2ND_NOT_ENCODED; ?>');
									suggestion.enableIcon(true);
									suggestion.init('permissionAddInput');
									//]]>
								</script>
								<input id="permissionAddButton" type="button" value="Add" />
							</div>
						</div>
						
						<div class="formElement" style="display: none;">
							<div class="formFieldLabel">
								<div id="permissionSettingsTitle" class="accessRightsTitle"></div>
							</div>
							<div class="formField">
								<div id="permissionHeader" class="accessRightsHeader">
									<span class="deny">Deny</span>
									<span class="allow">Allow</span>
								</div>
								<div id="permissionSettings" class="accessRights container-4"></div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>

			<?php if (isset($this->v['additionalTabContents'])) { ?><?php echo $this->v['additionalTabContents']; ?><?php } ?>
		</div>
	</div>

	<div class="formSubmit">
		<input type="submit" accesskey="s" value="Submit" />
		<input type="reset" accesskey="r" value="Reset" />
		<input type="hidden" name="packageID" value="<?php echo PACKAGE_ID; ?>" />
 		<?php echo SID_INPUT_TAG; ?>
 		<?php if (isset($this->v['boardID'])) { ?><input type="hidden" name="boardID" value="<?php echo $this->v['boardID']; ?>" /><?php } ?>
 		<input type="hidden" id="activeTabMenuItem" name="activeTabMenuItem" value="<?php echo StringUtil::encodeHTML($this->v['activeTabMenuItem']); ?>" />
 	</div>
</form>

<?php
$outerTemplateNamee3226ac500cb2719ab9e013b95a09573654d1e4e = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamee3226ac500cb2719ab9e013b95a09573654d1e4e;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>